---
title: "Access"
date: today
---

In [1]:
import pandas as pd
import polars as pl
import util
from pathlib import Path

pd.set_option('display.float_format', '{:,.0f}'.format)

In [2]:
transit_jobs_access = pd.read_csv(util.output_path / 'access/transit_jobs_access.csv', 
                                  usecols=['geography', 'value', 'geography_group'])
walk_bike_jobs_access = pd.read_csv(util.output_path / 'access/walk_bike_jobs_access.csv', 
                                  usecols=['geography_value', 'jobs_1_mile_walk', 'jobs_3_mile_bike', 'geography_group']).\
                                  rename(columns={'geography_value': 'geography'})

parcel_emp = util.get_parcels_urbansim_data(inc_geog=True)

# jobs access in equity geographies
equity_geogs = util.summary_config['equity_geogs']

## Jobs Accessible within 45 Minutes of Transit
Household-weighted average of number of jobs accessible within a geography

In [3]:
def process_access_data(jobs_access):
    df_access = jobs_access.copy()
    # rename region
    df_access.loc[jobs_access['geography_group'] == 'region', 'geography'] = 'Region'
    # rename rgc
    df_access.loc[jobs_access['geography_group'] == 'rgc_binary', 'geography'] = ['Not in RGC', 'In RGC']
    # rename regional geography
    df_access.loc[jobs_access['geography_group'] == 'rg_proposed', 'geography_group'] = 'RegionalGeogName'

    equity_geogs = list(util.equity_geog_dict.keys())
    df_access_equity = df_access.loc[
        df_access['geography_group'].isin(equity_geogs)].copy()
    
    df_access_equity['geography'] = df_access_equity['geography'].map({"0.0": 'Below Regional Average', 
                                                                       "1.0": 'Above Regional Average', 
                                                                       "2.0": 'Higher Share of Equity Population'}
                                                                       )
    df_access_equity['geography_group'] = df_access_equity['geography_group'].map(util.equity_geog_dict)

    # df_access_equity_geogs['geography'] = df_access_equity_geogs['geography_group']
    # df['geography'] = "NOT in " + df['geography_group']

    # df_access_equity_geogs = pd.concat([df_access_equity_geogs, df], ignore_index=True)
    # df_access_equity_geogs['geography_group'] = 'Equity Geography'

    return df_access, df_access_equity


df_access_t, df_access_equity_t = process_access_data(transit_jobs_access)
df_access_bp, df_access_equity_bp = process_access_data(walk_bike_jobs_access)
tot_jobs = parcel_emp['emptot_p'].sum()

:::{.panel-tabset}

### Region and County

In [4]:
def job_access_geog(access_table, geog, format=True):
    df = access_table.loc[access_table['geography_group'].isin([geog, 'region'])].\
        rename(columns={'value': 'Jobs within 45-minute Transit Commute'}).\
        drop(columns=['geography_group']).\
        set_index('geography')
    
    # df_jobs = parcel_emp.groupby(geog)['emptot_p'].sum()
    # df_jobs['Region'] = tot_jobs
    # df = pd.concat([df, df_jobs.rename('Total Jobs within Geography')], axis=1)
    # df = df.loc[df.index != 'Outside Region'].copy()

    df['% All Jobs'] = df['Jobs within 45-minute Transit Commute'] / tot_jobs
    # # df['% of Jobs in Geography'] = df['Jobs within 45-minute Transit Commute'] / df['Total Jobs within Geography']

    if format:
        return df.style.format('{:,.0f}', subset=['Jobs within 45-minute Transit Commute']).format('{:,.1%}', subset=['% All Jobs'])
    else:
        return df

    return df

In [5]:
df = job_access_geog(df_access_t,'CountyName')
# df = df[df.index != 'Outside Region']
df

### Regional Growth Center

In [6]:
df_rgc = job_access_geog(df_access_t,'rgc_binary')
df_rgc

In [7]:
df = job_access_geog(df_access_t,'GrowthCenterName')

df

### Regional Geography

In [8]:
job_access_geog(df_access_t,'RegionalGeogName')

### Equity Focus Areas

job_access_geog

In [9]:
df = pd.DataFrame()
for col, label in util.equity_geog_dict.items():
    _df = job_access_geog(df_access_equity_t, label, format=False)
    _df['Group'] = label
    df = pd.concat([df, _df])
df = df.reset_index()
df.rename(columns={'geography': 'EFA Type'}, inplace=True)
df["% All Jobs"] = df["Jobs within 45-minute Transit Commute"]/tot_jobs
df.loc[df['EFA Type']!="Region"][['Group', 'EFA Type', 'Jobs within 45-minute Transit Commute',"% All Jobs"]].style.\
        format('{:,.0f}', subset=['Jobs within 45-minute Transit Commute']).\
            format('{:,.1%}', subset=['% All Jobs'])
# df

:::

## Average Jobs Accessible within 1 Mile Walk and 3 Mile Bike
Note that this is not using the bike network, but is instead using the all-streets network.

Average accessible jobs are weighted averages based on parcel household population.

:::{.panel-tabset}

### Region and County

In [10]:
def bp_job_access_geog(access_table,geog):
    df = access_table.loc[access_table['geography_group'].isin(['region', geog])].\
        rename(columns={'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                        'jobs_3_mile_bike': 'Jobs within 3-mile Bike'}).\
        drop(columns=['geography_group']).\
        set_index('geography')

    df = df.fillna(0)

    df['% Total Jobs (1-mile walk)'] = df['Jobs within 1-mile Walk'].apply(lambda x: f'{x / tot_jobs * 100:,.1f}' + '%')
    df['% Total Jobs (3-mile bike)'] = df['Jobs within 3-mile Bike'].apply(lambda x: f'{x / tot_jobs * 100:,.1f}' + '%')

    return df

In [11]:
df = bp_job_access_geog(df_access_bp,'CountyName')
df = df[df.index != 'Outside Region']
df

,Jobs within 1-mile Walk,Jobs within 3-mile Bike,% Total Jobs (1-mile walk),% Total Jobs (3-mile bike)
geography,,,,
King,"18,516","84,913",0.9%,3.9%
Kitsap,"1,236","8,014",0.1%,0.4%
Pierce,"2,508","18,163",0.1%,0.8%
Snohomish,"2,006","17,703",0.1%,0.8%
Region,"11,164","54,254",0.5%,2.5%

### Regional Growth Center

In [12]:
df_rgc = bp_job_access_geog(df_access_bp,'rgc_binary')
df = bp_job_access_geog(df_access_bp,'GrowthCenterName')

pd.concat([df_rgc, df.loc[~df.index.isin(['Region','Not in RGC'])]], axis=0)

,Jobs within 1-mile Walk,Jobs within 3-mile Bike,% Total Jobs (1-mile walk),% Total Jobs (3-mile bike)
geography,,,,
Region,"11,164","54,254",0.5%,2.5%
Not in RGC,"2,887","34,802",0.1%,1.6%
In RGC,"88,212","235,331",4.1%,10.9%
Auburn,"9,704","39,503",0.5%,1.8%
Bellevue,"59,188","110,699",2.7%,5.1%
Bothell Canyon Park,"8,539","21,748",0.4%,1.0%
Bremerton,"11,536","34,387",0.5%,1.6%
Burien,"4,836","13,421",0.2%,0.6%
Everett,"15,908","39,722",0.7%,1.8%
Federal Way,"6,348","26,221",0.3%,1.2%
Greater Downtown Kirkland,"12,208","36,556",0.6%,1.7%
Issaquah,0,0,0.0%,0.0%
Kent,"10,478","45,920",0.5%,2.1%
Kirkland Totem Lake,"8,528","33,064",0.4%,1.5%
Lakewood,"6,423","25,300",0.3%,1.2%
Lynnwood,"9,274","46,089",0.4%,2.1%
Puyallup Downtown,"7,643","31,585",0.4%,1.5%
Puyallup South Hill,"5,820","20,224",0.3%,0.9%
Redmond Downtown,"14,340","73,341",0.7%,3.4%
Redmond-Overlake,"40,768","104,969",1.9%,4.9%
Renton,"12,653","54,485",0.6%,2.5%
SeaTac,"12,354","57,127",0.6%,2.7%
Seattle Downtown,"201,230","411,627",9.3%,19.1%
Seattle First Hill/Capitol Hill,"138,091","403,217",6.4%,18.7%
Seattle Northgate,"8,682","41,922",0.4%,1.9%
Seattle South Lake Union,"154,182","410,001",7.2%,19.0%
Seattle University District,"24,298","107,782",1.1%,5.0%
Seattle Uptown,"68,197","396,272",3.2%,18.4%
Silverdale,"5,110","10,508",0.2%,0.5%
Tacoma Downtown,"30,153","79,404",1.4%,3.7%
Tacoma Mall,"10,265","51,559",0.5%,2.4%
Tukwila,"19,149","87,604",0.9%,4.1%
University Place,"2,882","15,898",0.1%,0.7%

### Regional Geography

In [13]:
bp_job_access_geog(df_access_bp,'RegionalGeogName')

,Jobs within 1-mile Walk,Jobs within 3-mile Bike,% Total Jobs (1-mile walk),% Total Jobs (3-mile bike)
geography,,,,
Region,"11,164","54,254",0.5%,2.5%
Cities and Towns,984,"8,948",0.0%,0.4%
Core Cities,"3,415","28,587",0.2%,1.3%
High Capacity Transit Communities,"1,428","15,237",0.1%,0.7%
Metropolitan Cities,"29,432","128,074",1.4%,5.9%
Rural Areas,142,"2,387",0.0%,0.1%
Urban Unincorporated Areas,443,"6,816",0.0%,0.3%

### Equity Focus Areas

In [14]:
df = pd.DataFrame()
for col, label in util.equity_geog_dict.items():
    _df = bp_job_access_geog(df_access_equity_bp, label)
    _df['Group'] = label
    df = pd.concat([df, _df])
df = df.reset_index()
df.rename(columns={'geography': 'EFA Type'}, inplace=True)
df[['Group', 'EFA Type', 'Jobs within 1-mile Walk',	'Jobs within 3-mile Bike',	'% Total Jobs (1-mile walk)','% Total Jobs (3-mile bike)']]

,Group,EFA Type,Jobs within 1-mile Walk,Jobs within 3-mile Bike,% Total Jobs (1-mile walk),% Total Jobs (3-mile bike)
0,People of Color,Below Regional Average,"5,374","41,935",0.2%,1.9%
1,People of Color,Above Regional Average,"18,509","71,731",0.9%,3.3%
2,People of Color,Higher Share of Equity Population,"17,229","63,994",0.8%,3.0%
3,Income,Below Regional Average,"9,394","52,420",0.4%,2.4%
4,Income,Above Regional Average,"13,899","56,258",0.6%,2.6%
5,Income,Higher Share of Equity Population,"13,651","58,320",0.6%,2.7%
6,LEP,Below Regional Average,"11,368","57,818",0.5%,2.7%
7,LEP,Above Regional Average,"13,284","51,842",0.6%,2.4%
8,LEP,Higher Share of Equity Population,"7,745","43,674",0.4%,2.0%
9,Disability,Below Regional Average,"9,651","56,870",0.4%,2.6%
10,Disability,Above Regional Average,"10,572","45,877",0.5%,2.1%
11,Disability,Higher Share of Equity Population,"17,706","61,620",0.8%,2.9%
12,Older Adults,Below Regional Average,"13,534","66,876",0.6%,3.1%
13,Older Adults,Above Regional Average,"9,416","44,070",0.4%,2.0%
14,Older Adults,Higher Share of Equity Population,"6,365","30,873",0.3%,1.4%
15,Youth,Below Regional Average,"18,907","83,073",0.9%,3.9%
16,Youth,Above Regional Average,"1,974","21,537",0.1%,1.0%
17,Youth,Higher Share of Equity Population,"1,054","12,729",0.0%,0.6%

:::

## Intersection Density

In [15]:
buffered_parcels = pl.read_csv(util.output_path / 'landuse/buffered_parcels.txt', 
                               separator=' ',
                               columns=['parcelid','nodes3_2','nodes4_2','hh_p']).to_pandas()


list_cols = ['ParcelID','CountyName','GrowthCenterName','rg_proposed'] + equity_geogs
parcel_geog = util.get_parcel_geog()[list_cols]

In [16]:
df_intersection = buffered_parcels.merge(parcel_geog, left_on='parcelid', right_on='ParcelID')

# Total intersections within 1/2 mile buffer
df_intersection['intersections_wt'] = (df_intersection['nodes3_2'] + df_intersection['nodes4_2']) * df_intersection['hh_p']

In [17]:
def intersection_density(geog, map=False):
    df = df_intersection.groupby(geog)[['intersections_wt', 'hh_p']].sum().reset_index()
    df['Intersections'] = df['intersections_wt']/df['hh_p']

    if map:
        df[geog] = df[geog].astype('int').map({0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'}
                                )
    
    return df[[geog] + ['Intersections']]

:::{.panel-tabset}

### County

In [18]:
df = intersection_density('CountyName')
df = df[df['CountyName']!='Outside Region']
df

  CountyName  Intersections
0       King            155
1     Kitsap             51
3     Pierce             80
4  Snohomish             73

### Regional Growth Center

In [19]:
intersection_density('GrowthCenterName')

                   GrowthCenterName  Intersections
0                            Auburn            168
1                          Bellevue            273
2               Bothell Canyon Park             69
3                         Bremerton            168
4                            Burien            176
5                           Everett            161
6                       Federal Way            134
7         Greater Downtown Kirkland            167
8                          Issaquah            NaN
9                              Kent            214
10              Kirkland Totem Lake            124
11                         Lakewood            121
12                         Lynnwood            139
13                       Not in RGC            100
14                Puyallup Downtown            183
15              Puyallup South Hill             65
16                 Redmond Downtown            223
17                 Redmond-Overlake            153
18                           Renton            199
19                           SeaTac            109
20                 Seattle Downtown            419
21  Seattle First Hill/Capitol Hill            404
22                Seattle Northgate            175
23         Seattle South Lake Union            356
24      Seattle University District            284
25                   Seattle Uptown            281
26                       Silverdale             79
27                  Tacoma Downtown            203
28                      Tacoma Mall            103
29                          Tukwila            114
30                 University Place            109

### Regional Geography

In [20]:
intersection_density('rg_proposed')

                         rg_proposed  Intersections
0                   Cities and Towns             65
1                        Core Cities            103
2  High Capacity Transit Communities             84
3                Metropolitan Cities            202
4                        Rural Areas             20
5         Urban Unincorporated Areas             56

### Equity Focus Areas

In [21]:
df = pd.DataFrame()
for col, label in util.equity_geog_dict.items():
    _df = intersection_density(col).rename(columns={col: "Group"})
    _df['Group'] = label
    df = pd.concat([df, _df])
df = df.reset_index()
df['EFA Type'] = df['index'].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })
df[['Group', 'EFA Type', 'Intersections']]

              Group                           EFA Type  Intersections
0   People of Color             Below Regional Average            103
1   People of Color             Above Regional Average            136
2   People of Color  Higher Share of Equity Population            136
3            Income             Below Regional Average            112
4            Income             Above Regional Average            122
5            Income  Higher Share of Equity Population            137
6               LEP             Below Regional Average            117
7               LEP             Above Regional Average            120
8               LEP  Higher Share of Equity Population            121
9        Disability             Below Regional Average            121
10       Disability             Above Regional Average            110
11       Disability  Higher Share of Equity Population            126
12     Older Adults             Below Regional Average            134
13     Older Adults             Above Regional Average            105
14     Older Adults  Higher Share of Equity Population             92
15            Youth             Below Regional Average            152
16            Youth             Above Regional Average             81
17            Youth  Higher Share of Equity Population             69

:::