In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": True, "run_validation": True, "run_network_validation": True, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "daysim-validation-notebook": ["all_tour_mode", "all_trip_mode", "auto_ownership", "day_pattern", "escort_tour_mode", "escort_trip_mode", "households", "intermediate_stop_generation", "other_home_based_tour_mode", "other_home_based_trip_mode", "persons", "school_location", "school_tour_mode", "school_trip_mode", "telecommute", "time_choice", "tours", "tour_destination", "transit_pass_ownership", "trips", "trip_destination", "workbased_subtour_generation", "workbased_subtour_mode", "work_location", "work_tour_mode", "work_trip_mode"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "../../../../inputs/base_year/survey"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to6": 5, "6to7": 6, "7to8": 7, "8to9": 8, "9to10": 9, "10to14": 10, "14to15": 14, "15to16": 15, "16to17": 16, "17to18": 17, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "base_year_2023_final", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/rtp_2026_2050", "abm_model": "daysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_daysim": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": True, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}

---
title: "Transit"
date: today
---

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np
import polars as pl
import geopandas as gpd
import h5py
import util

%matplotlib inline
from IPython.display import display, HTML

relative_path = Path('../../../..')

pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:0,.0f}'.format

## Transit Boardings

:::{.panel-tabset}
### Agency

In [3]:

df = pd.read_csv(util.output_path / 'transit/daily_boardings_by_agency.csv',index_col=0)
df.loc['Region Total','boardings'] = df['boardings'].sum()
df = df.reset_index()
df.rename(columns={'agency_name': 'Agency', 'boardings': 'Boardings'}, inplace=True)
HTML(df.to_html(index=False))

### Service Type

In [4]:
df = pd.read_csv(util.output_path / 'transit/transit_line_results.csv',index_col=0)

transit_type_map = {
    1: 'Local Bus',
    2: 'Express Bus',
    3: 'Bus Rapid Transit',
    4: 'Streetcar',
    5: 'Commuter Rail',
    6: 'Light Rail',
    7: 'Auto Ferry',
    8: 'Passenger Ferry'
}
df['transit_type'] = df['transit_type'].map(transit_type_map)
df = df.groupby('transit_type').sum()[['boardings']]
df.loc['Total'] = df.sum(axis=0)
df = df.reset_index()
df.rename(columns={'boardings':' Boardings','transit_type':'Transit Type'}, inplace=True)
HTML(df.to_html(index=False))

### Sound Transit Modes

In [5]:
df = pd.read_csv(util.output_path / 'transit/transit_line_results.csv',index_col=0)
df = df[(df['agency_code']==6)].groupby('transit_type').sum()[['boardings']]
df.index = df.index.map({1: 'Bus', 3: 'BRT (Stride)', 5: 'Commuter Rail', 6: 'Light Rail'})
df.rename(columns={'boardings':' Boardings'}, inplace=True)

df

               Boardings
transit_type
Bus               42,841
Commuter Rail      7,056
Light Rail        87,126

### Light Rail

:::{.panel-tabset}

#### Boardings by Station

In [6]:
# all transit stop locations
df_transit_stops = pd.read_csv(util.input_path / 'scenario/networks/transit_stops.csv', usecols = ['PSRCJunctID', 'x', 'y','light_rail'])

# Load station names
df_lr_station_names = util.read_sqlite_db("SELECT * FROM light_rail_stations_2050")

# Merge station names to df 
light_rail_stations = df_transit_stops[df_transit_stops['light_rail']==1].\
    merge(df_lr_station_names, left_on=['PSRCJunctID'], right_on=['Station Node'])

In [7]:
# Light rail boardings by station
df_boardings = pd.read_csv(util.output_path / 'transit/boardings_by_stop.csv')
df = pd.merge(df_boardings, light_rail_stations, left_on=['i_node'], right_on=['PSRCJunctID'])

df = df[['total_boardings','Station Name','PSRCJunctID']]#.drop_duplicates()

# pivot table of boardings by station 
df[['PSRCJunctID','Station Name','total_boardings']]

    PSRCJunctID                 Station Name  total_boardings
0        197649                Husky Stadium            4,123
1        198007                     Westlake            9,768
2        198009                     Symphony            6,076
3        198011               Pioneer Square            5,260
4        198013               Int'l District            1,749
5        198014                 Capitol Hill            7,549
6        198015                      Stadium              525
7        198016                         SODO            3,385
8        198017                  Beacon Hill            1,474
9        198018                  Mount Baker            1,586
10       198019                Columbia City            1,665
11       198020                      Othello            2,162
12       198021                Rainier Beach            1,812
13       198022           Tukwila Int'l Blvd            3,117
14       198023               SeaTac/Airport            6,424
15       198024                   Angle Lake            2,298
16       198040          Tacoma Dome Station              276
17       198041            S 25th St Station              524
18       198042                Union Station              258
19       198043    Convention Center Station              666
20       198044             Commerce Station              464
21       198067  University District Station            8,462
22       198068            Roosevelt Station            8,302
23       198069            Northgate Station            9,202

#### Boardings by Line

In [8]:
# Light rail boardings by segment
df = pd.read_csv(util.output_path / 'transit/transit_line_results.csv', usecols = ['line_id','mode','description'])
df_light_rail = df[(df['mode']=="r") & (df['description']!="Streetcar-South Lake")].copy().\
    drop_duplicates()
df_light_rail['description'] = df_light_rail['description'].str[:6]
df_light_rail.rename(columns={'description':'Line'}, inplace=True)

In [9]:
# Light rail boardings by segment
df_boardings = pd.read_csv(util.output_path / 'transit/transit_segment_results.csv')

# get line and depart station names
df = df_boardings.merge(df_lr_station_names, left_on=['i_node'], right_on=['Station Node']).\
    merge(df_light_rail, on=['line_id'])

# all station boardings by line
board_station_line = df.groupby(['Line','Station Name'])['segment_boarding'].sum().reset_index()

In [10]:
board_station_line.groupby('Line')['segment_boarding'].sum().\
    reset_index().set_index('Line').\
    rename(columns={'segment_boarding':'Total Boardings'})

        Total Boardings
Line
Light            87,126

#### 1 Line Boardings

In [11]:
def get_stop_boardings(line_name):
    df = board_station_line[board_station_line['Line']==line_name]
    df2 = df.groupby('Line').sum()['segment_boarding'].reset_index()
    df2['Station Name'] = 'Total'
    return pd.concat([df2[["Line", "Station Name", "segment_boarding"]],df], ignore_index=True)

get_stop_boardings('1 Line')

Empty DataFrame
Columns: [Line, Station Name, segment_boarding]
Index: []

#### 2 Line Boardings

In [12]:
get_stop_boardings('2 Line')

Empty DataFrame
Columns: [Line, Station Name, segment_boarding]
Index: []

#### 3 Line Boardings

In [13]:
get_stop_boardings('3 Line')

Empty DataFrame
Columns: [Line, Station Name, segment_boarding]
Index: []

#### 4 Line Boardings

In [14]:
get_stop_boardings('4 Line')

Empty DataFrame
Columns: [Line, Station Name, segment_boarding]
Index: []

#### T Line Boardings

In [15]:
get_stop_boardings('T Line')

Empty DataFrame
Columns: [Line, Station Name, segment_boarding]
Index: []

:::

### Trips by Submode

In [16]:
df = pd.read_csv(util.output_path / 'transit/total_transit_trips.csv',index_col=0)
df.rename(index={'commuter_rail': 'Commuter Rail',
                'litrat': 'Light Rail',
                'ferry': 'Auto Ferry',
                'passenger_ferry': 'Passenger Ferry',
                'trnst': 'Bus'}, inplace=True)
df.columns = ['Total Trips']
df.loc['Total'] = df.sum(axis=0)
df.reset_index(inplace=True)
df.rename(columns={'index': 'Transit Type'}, inplace=True)
HTML(df.to_html(index=False))

:::

## Households Near HCT

In [17]:
# List of Stations
# Load transit stops file

#"The definition we have been using for the RTP is BRT, LRT, Commuter Rail, StreetCar and Ferry."
df = pd.read_csv(util.input_path / 'scenario/networks/transit_stops.csv')
# Streetcar is coded as light rail
df['hct'] = 0
df.loc[df[['commuter_rail','light_rail','ferry','brt']].sum(axis=1) > 0,'hct'] = 1
df_hct = df[df['hct'] == 1]

# Map of Stations
# Load as a geodataframe
gdf_hct = gpd.GeoDataFrame(
    df_hct, geometry=gpd.points_from_xy(df_hct.x, df_hct.y))

gdf_hct.crs = 'EPSG:2285'

In [18]:
df_lu = util.get_parcels_urbansim_data(inc_geog=True)
parcel_geog = util.get_parcel_geog()

# Load as a geodataframe
gdf_lu = gpd.GeoDataFrame(
    df_lu, geometry=gpd.points_from_xy(df_lu.xcoord_p, df_lu.ycoord_p))

gdf_lu.crs = 'EPSG:2285'

In [19]:
# Add a field that defines whether a parcel is inside (1) or outside (0) any RGC
df_lu['RGC_binary'] = 0
df_lu.loc[df_lu['GrowthCenterName'] != 'Not in RGC', 'RGC_binary'] = 1

In [20]:
def calculate_buffer(gdf_lu, _gdf_hct, distance):
    
    # Buffer the HCT station gdf
    _gdf_hct['geometry'] = _gdf_hct.buffer(distance)

    gdf_intersect = gpd.overlay(_gdf_hct, gdf_lu, how="intersection", keep_geom_type=False)
    df = df_lu[df_lu['parcelid'].isin(gdf_intersect['parcelid'].unique())]
    
    return df, gdf_intersect

def aggregate_parcels(df, col_dict, sum_field):
    results_df = pd.DataFrame()
    for col, name in col_dict.items():
        _df = df[[col,sum_field]].groupby(col).sum()[[sum_field]]
        _df['group'] = name
        results_df = pd.concat([results_df,_df])
    results_df = results_df.reset_index()
    
    return results_df

In [21]:
df_025, gdf_025 = calculate_buffer(gdf_lu, gdf_hct.copy(), distance=5280.0/4)

In [22]:
df_050, gdf_050 = calculate_buffer(gdf_lu, gdf_hct.copy(), distance=5280.0/2)

In [23]:
pd.options.display.float_format = '{:0,.0f}'.format
col_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability',
           'rg_proposed': 'Regional Geography',
            'CountyName': 'County',
            'GrowthCenterName': 'Regional Growth Center',
            'RGC_binary': 'RGC Binary',
            'Region': 'Region'
           }

hct_hh_df = pd.DataFrame()
df_025 = df_025.copy()
df_025['Region'] = 1
df = aggregate_parcels(df_025, col_dict, 'hh_p')
df['distance'] = 0.25
hct_hh_df = pd.concat([hct_hh_df,df])
df_050 = df_050.copy()
df_050['Region'] = 1
df = aggregate_parcels(df_050, col_dict, 'hh_p')
df['distance'] = 0.50
hct_hh_df = pd.concat([hct_hh_df,df])

In [24]:
pd.options.display.float_format = '{:0,.0f}'.format

:::{.panel-tabset}

### Region

In [25]:

df = hct_hh_df[hct_hh_df['group'] == 'Region']
df = df.rename(columns={'hh_p': 'Total'}).copy()
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Region'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df = df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'})

df['% of Households (1/4 Mile)'] = df['1/4 Mile']/df_lu['hh_p'].sum()
df['% of Households (1/2 Mile)'] = df['1/2 Mile']/df_lu['hh_p'].sum()

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### County

In [26]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'County'].copy()
df = df.rename(columns={'hh_p': 'Total'}).copy()
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'County'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

_df = df.merge(df_lu[['CountyName','hh_p']].groupby('CountyName').sum()[['hh_p']].reset_index(),left_on='County', right_on='CountyName')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['County', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='County')

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Growth Center

In [27]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'RGC Binary'].copy()
df.rename(columns={'hh_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'RGC Binary'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)


_df = df.merge(df_lu[['RGC_binary','hh_p']].groupby('RGC_binary').sum()[['hh_p']].reset_index(),left_on='RGC Binary', 
               right_on='RGC_binary')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['RGC Binary', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='RGC Binary')
df['RGC Designation'] = df['RGC Binary'].map({0: 'Outside RGC', 1: 'Inside RGC'})
df = df[['RGC Designation','1/4 Mile','1/2 Mile','% of Households (1/4 Mile)', '% of Households (1/2 Mile)']]
output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

In [28]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'Regional Growth Center'].copy()
df.rename(columns={'hh_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Growth Center'
# Ensure all RGCs are included, even those that have no HCT access
for center in parcel_geog['GrowthCenterName'].unique():
    if center not in df.index:
        df.loc[center] = 0

df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

# Calcualte the percent of households in this geography within 1/4 and 1/2 mile
_df = df.merge(df_lu[['GrowthCenterName','hh_p']].groupby('GrowthCenterName').sum()[['hh_p']].reset_index(),left_on='Regional Growth Center', 
               right_on='GrowthCenterName')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['Regional Growth Center', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='Regional Growth Center')

df = df.sort_values('Regional Growth Center')

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Geography

In [29]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'Regional Geography'].copy()
df.rename(columns={'hh_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Geography'
df.reset_index(inplace=True)

df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
HTML(df.to_html(index=False))

_df = df.merge(df_lu[['rg_proposed','hh_p']].groupby('rg_proposed').sum()[['hh_p']].reset_index(),left_on='Regional Geography', 
               right_on='rg_proposed')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['Regional Geography', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='Regional Geography')

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Equity Geography

In [30]:
pd.options.display.float_format = '{:0,.2f}'.format
# df = hct_hh_df.copy()
# df = df[df['index'] == 1]
# df.rename(columns={'hh_p': 'Total'}, inplace=True)
# df.drop('index', axis=1, inplace=True)
# df = df.pivot_table(index='group', columns='distance', values='Total', aggfunc='sum')
# df[0.25] = df[0.25].astype('float32')
# df[0.5] = df[0.5].astype('float32')
# df.index.name = 'Equity Geography'
# df = df.reset_index()
# df = df.rename_axis(None, axis=1)
# df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

In [31]:
pd.options.display.float_format = '{:0,.1f}'.format

equity_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability'}

df = hct_hh_df[hct_hh_df['group'].isin(equity_dict.values())].copy()
df['EFA Type'] = df['index'].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

df = df.pivot_table(index=['group','EFA Type'], columns='distance', values='hh_p', aggfunc='sum').reset_index()

# Merge with total households to get shares of group
efa_pop_tot = df_lu[equity_dict.keys()].sum().to_dict()

for lu_col, label in equity_dict.items():
    df.loc[df['group'] == label, "Total Pop"] = efa_pop_tot[lu_col]
df['% of Households (1/4 Mile)'] = df[0.25]/df['Total Pop']
df['% of Households (1/2 Mile)'] = df[0.5]/df['Total Pop']

df.rename(columns={'group': 'Group', 0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df = df.rename_axis(None, axis=1)
df.drop('Total Pop', inplace=True, axis=1)
output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

:::

## Jobs Near HCT

In [32]:
pd.options.display.float_format = '{:0,.0f}'.format
col_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability',
           'rg_proposed': 'Regional Geography',
            'CountyName': 'County',
            'GrowthCenterName': 'Regional Growth Center',
            'RGC_binary': 'RGC Binary',
            'Region': 'Region'
           }

hct_hh_df = pd.DataFrame()
df_025['Region'] = 1
df = aggregate_parcels(df_025, col_dict, 'emptot_p')
df['distance'] = 0.25
hct_hh_df = pd.concat([hct_hh_df,df])
df_050['Region'] = 1
df = aggregate_parcels(df_050, col_dict, 'emptot_p')
df['distance'] = 0.50
hct_hh_df = pd.concat([hct_hh_df,df])


:::{.panel-tabset}
### Region

In [33]:

df = hct_hh_df[hct_hh_df['group'] == 'Region'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Region'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

df['% of Jobs (1/4 Mile)'] = df['1/4 Mile']/df_lu['emptot_p'].sum()
df['% of Jobs (1/2 Mile)'] = df['1/2 Mile']/df_lu['emptot_p'].sum()

output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### County

In [34]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'County'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'County'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

_df = df.merge(df_lu[['CountyName','emptot_p']].groupby('CountyName').sum()[['emptot_p']].reset_index(),left_on='County', right_on='CountyName')
_df['% of Jobs (1/4 Mile)'] = _df['1/4 Mile']/_df['emptot_p']
_df['% of Jobs (1/2 Mile)'] = _df['1/2 Mile']/_df['emptot_p']

df = df.merge(_df[['County', '% of Jobs (1/4 Mile)', '% of Jobs (1/2 Mile)']], 
              on='County')

output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Growth Center

In [35]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'RGC Binary'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'RGC Binary'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)


_df = df.merge(df_lu[['RGC_binary','emptot_p']].groupby('RGC_binary').sum()[['emptot_p']].reset_index(),left_on='RGC Binary', 
               right_on='RGC_binary')
_df['% of Jobs (1/4 Mile)'] = _df['1/4 Mile']/_df['emptot_p']
_df['% of Jobs (1/2 Mile)'] = _df['1/2 Mile']/_df['emptot_p']

df = df.merge(_df[['RGC Binary', '% of Jobs (1/4 Mile)', '% of Jobs (1/2 Mile)']], 
              on='RGC Binary')
df['RGC Designation'] = df['RGC Binary'].map({0: 'Outside RGC', 1: 'Inside RGC'})
df = df[['RGC Designation','1/4 Mile','1/2 Mile','% of Jobs (1/4 Mile)', '% of Jobs (1/2 Mile)']]
output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

In [36]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'Regional Growth Center'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Growth Center'
# Ensure all RGCs are included, even those that have no HCT access
for center in parcel_geog['GrowthCenterName'].unique():
    if center not in df.index:
        df.loc[center] = 0
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df['% of Total Jobs (1/4 Mile)'] = df['1/4 Mile']/df_lu['emptot_p'].sum()
df['% of Total Jobs (1/2 Mile)'] = df['1/2 Mile']/df_lu['emptot_p'].sum()

output = df.to_html(formatters={
    '% of Total Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Total Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Geography

In [37]:
df = hct_hh_df[hct_hh_df['group'] == 'Regional Geography'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Geography'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df['% of Total Jobs (1/4 Mile)'] = df['1/4 Mile']/df_lu['emptot_p'].sum()
df['% of Total Jobs (1/2 Mile)'] = df['1/2 Mile']/df_lu['emptot_p'].sum()

output = df.to_html(formatters={
    '% of Total Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Total Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Equity Geography

In [38]:
pd.options.display.float_format = '{:0,.0f}'.format

equity_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability'}

df = hct_hh_df[hct_hh_df['group'].isin(equity_dict.values())].copy()
df['EFA Type'] = df['index'].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

df = df.pivot_table(index=['group','EFA Type'], columns='distance', values='emptot_p', aggfunc='sum').reset_index()

# Merge with total households to get shares of group
efa_pop_tot = df_lu[equity_dict.keys()].sum().to_dict()

df[0.25] = df[0.25].astype("float")
df[0.50] = df[0.50].astype("float")

for lu_col, label in equity_dict.items():
    df.loc[df['group'] == label, "Total Jobs"] = efa_pop_tot[lu_col]
df['% of Households (1/4 Mile)'] = df[0.25]/df['Total Jobs']
df['% of Households (1/2 Mile)'] = df[0.5]/df['Total Jobs']


df.rename(columns={'group': 'Group', 0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df = df.rename_axis(None, axis=1)
df.drop('Total Jobs', inplace=True, axis=1)
output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

:::

## Transit Access Mode
Percent of Transit Trips Accessed by Walking

:::{.panel-tabset}
### Region

In [39]:
pd.options.display.float_format = '{:0,.1%}'.format
df = pd.read_csv(util.output_path / 'agg/dash/trip_mode_by_tour_mode.csv')
_df = df.copy()
pnr_transit_trips = _df[(_df['tmodetp'] == 'Park') & (_df['mode'] == 'Transit')]['trexpfac'].sum()
walk_transit_trips = _df[(_df['tmodetp'] == 'Transit') & (_df['mode'] == 'Transit')]['trexpfac'].sum()
reg_access = (walk_transit_trips/(walk_transit_trips+pnr_transit_trips))
pd.DataFrame([reg_access], columns=['% Transit trips Accessed by Walking'], index=['Region'])

        % Transit trips Accessed by Walking
Region                                95.0%

### Equity Geographies

In [40]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = df.copy()
results_df = pd.DataFrame()
list_50 = ['hh_racial','hh_poverty']
# for col in ['hh_disability','hh_elderly','hh_english','hh_poverty','hh_racial','hh_youth']:
for col in util.summary_config["hh_equity_geogs"]:
    pnr_transit_trips = _df[(_df[col] == 1) & 
                            (_df['tmodetp'] == 'Park') &
                            (_df['mode'] == 'Transit')]['trexpfac'].sum()
    walk_transit_trips = _df[(_df[col] == 1) & 
                                (_df['tmodetp'] == 'Transit') & 
                                (_df['mode'] == 'Transit')]['trexpfac'].sum()
    if (pnr_transit_trips > 0) & (walk_transit_trips > 0):
        results_df.loc[col,'% Transit Trips Accessed by Walking'] = walk_transit_trips/(walk_transit_trips+pnr_transit_trips)
# results_df.rename(columns={'_reg':'> Regional Average', '_50': '> 50%'}, inplace=True)
results_df

               % Transit Trips Accessed by Walking
hh_efa_dis                                   95.7%
hh_efa_older                                 95.2%
hh_efa_lep                                   95.6%
hh_efa_pov200                                95.8%
hh_efa_poc                                   96.1%
hh_efa_youth                                 93.3%

:::

## Transit Equity

### Trip purpose by transit mode type

In [41]:
myh5 = h5py.File(util.input_path / 'scenario/landuse/hh_and_persons.h5', 'r')
person = pd.read_csv(util.output_path / 'daysim/_person.tsv', sep='\t')
df_trip = pd.read_csv(util.output_path / 'daysim/_trip.tsv', sep='\t')
df_hh = pd.read_csv(util.output_path / 'daysim/_household.tsv', sep='\t')

In [42]:
# Create a DataFrame from the h5 file
df_person = pd.DataFrame()
for col in ['hhno','pno','prace']:
    df_person[col] = myh5['Person'][col][:]

df_trip = df_trip.merge(df_person[['hhno','pno','prace']], on=['hhno','pno'], how='left')

In [43]:
# Create group of work, school, and all other purposes
df_trip['Purpose Type'] = 'Other'
df_trip.loc[df_trip['dpurp']==0, 'Purpose Type'] = 'Home'
df_trip.loc[df_trip['dpurp']==1, 'Purpose Type'] = 'Work'
df_trip.loc[df_trip['dpurp']==2, 'Purpose Type'] = 'School'

# Rename path types
df_trip.loc[df_trip['pathtype']==1, 'Path Type'] = 'Drive'
df_trip.loc[df_trip['pathtype']==3, 'Path Type'] = 'Bus'
df_trip.loc[df_trip['pathtype']==4, 'Path Type'] = 'Light Rail'
df_trip.loc[df_trip['pathtype']==5, 'Path Type'] = 'Ferry 1'
df_trip.loc[df_trip['pathtype']==6, 'Path Type'] = 'Commuter Rail'
df_trip.loc[df_trip['pathtype']==7, 'Path Type'] = 'Ferry 2'

df = pd.pivot_table(df_trip[(df_trip['dpurp']!=0) & (~df_trip['pathtype'].isin([0,'Drive']))], values='trexpfac', index='Path Type', columns='Purpose Type', aggfunc='sum')

df['Total'] = df.sum(axis=1)
for row in df.index:
    for col in ['Work','School','Other']:
        df.loc[row, col + ' %'] = df.loc[row, col] / df.loc[row, 'Total']

df[['Work %','School %','Other %']] = df[['Work %','School %','Other %']].map("{:,.1%}".format)
df[['Work %','School %','Other %']]

Purpose Type  Work % School % Other %
Path Type
Bus            16.0%    14.8%   69.2%
Commuter Rail  51.9%     2.1%   46.0%
Drive          20.2%     6.2%   73.6%
Ferry 1        42.1%    14.2%   43.7%
Ferry 2        60.0%     1.7%   38.3%
Light Rail     32.1%    13.9%   53.9%

In [44]:

race_dict = {
    '1': 'White alone',
    '2': 'Black or African American alone',
    '3': 'American Indian alone',
    '4': 'Alaska Native alone',
    '5': 'American Indian and Alaska Native tribes specified',
    '6': 'Asian alone',
    '7': 'Native Hawaiian and Other Pacific Islander alone',
    '8': 'Some Other Race alone',
    '9': 'Two or More Races'
}


df_trip['Race'] = df_trip['prace'].astype('int').astype('str').map(race_dict)

### Transit type distribution by race of rider

In [45]:
# Submode Ridership by race
df = pd.pivot_table(df_trip[(df_trip['pathtype']!="Drive")], values='trexpfac', index='Path Type', columns='Race', aggfunc="sum")
race_cols = ['White alone','Black or African American alone','American Indian alone',
             'Alaska Native alone','American Indian and Alaska Native tribes specified','Asian alone',
             'Native Hawaiian and Other Pacific Islander alone','Some Other Race alone','Two or More Races']
# Calculate shares of total by Race for each Path Type
df['Total'] = df.sum(axis=1)
df = df.astype('float')
for row in df.index:
    for col in race_cols:
        df.loc[row, col] = df.loc[row, col] / df.loc[row, 'Total']
df[race_cols] = df[race_cols].map("{:,.1%}".format)
df[race_cols]

Race,White alone,Black or African American alone,American Indian alone,Alaska Native alone,American Indian and Alaska Native tribes specified,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Two or More Races
Path Type,,,,,,,,,
Bus,58.8%,7.7%,0.5%,0.1%,0.1%,18.9%,0.7%,4.1%,9.1%
Commuter Rail,63.1%,7.8%,0.9%,0.0%,0.1%,11.6%,2.1%,5.5%,9.0%
Drive,64.6%,5.6%,0.6%,0.1%,0.1%,14.8%,1.0%,4.3%,9.0%
Ferry 1,79.3%,1.4%,0.5%,nan%,0.2%,5.8%,1.5%,2.8%,8.5%
Ferry 2,80.8%,2.3%,0.8%,0.2%,0.1%,5.0%,1.0%,2.3%,7.5%
Light Rail,57.1%,8.9%,0.6%,0.1%,0.1%,20.5%,0.5%,3.6%,8.6%

In [46]:
df_trip = df_trip.merge(df_hh[['hhno','hhincome']], on=['hhno'], how='left')

### Income distribution by household income of rider

In [47]:
# Create bins for hhincome
bins = [0, 20000, 40000, 60000, 80000, 100000, 120000, 140000, 160000, 180000, 200000, np.inf]
labels = ['<20k', '20-40k', '40-60k', '60-80k', '80-100k', '100-120k', '120-140k', '140-160k', '160-180k', '180-200k', '>200k']
df_trip['Income Bin'] = pd.cut(df_trip['hhincome'], bins=bins, labels=labels, right=False)
df_trip['Income Bin'] = df_trip['Income Bin'].astype('str')

# Transit Submodes by Income
df = pd.pivot_table(df_trip[(df_trip['Path Type']!="Drive")], values='trexpfac', index='Path Type', columns='Income Bin', aggfunc="sum")

# display labels with no significant figs
df[labels] = df[labels].map("{:0,.0f}".format)
df[labels]

Income Bin,<20k,20-40k,40-60k,60-80k,80-100k,100-120k,120-140k,140-160k,160-180k,180-200k,>200k
Path Type,,,,,,,,,,,
Bus,"35,509","27,537","23,049","20,388","19,356","14,904","14,292","13,350","10,829","9,614","59,636"
Commuter Rail,179,369,616,671,897,789,750,648,511,477,"1,832"
Ferry 1,211,259,345,401,376,346,337,280,258,210,853
Ferry 2,170,429,704,"1,067","1,073","1,151","1,004",919,756,691,"3,769"
Light Rail,"8,946","6,905","6,502","6,301","6,043","4,863","4,834","4,506","3,691","3,061","22,635"

In [48]:
pd.pivot_table(
    df_trip[df_trip['Path Type'] != "Drive"],
    values='hhincome',
    index='Path Type',
    aggfunc="median"
).astype(int).map(lambda x: "${:,.0f}".format(x))

               hhincome
Path Type
Bus             $98,292
Commuter Rail  $128,114
Ferry 1        $119,959
Ferry 2        $146,027
Light Rail     $118,413