In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": True, "run_validation": True, "run_network_validation": True, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "daysim-validation-notebook": ["all_tour_mode", "all_trip_mode", "auto_ownership", "day_pattern", "escort_tour_mode", "escort_trip_mode", "households", "intermediate_stop_generation", "other_home_based_tour_mode", "other_home_based_trip_mode", "persons", "school_location", "school_tour_mode", "school_trip_mode", "telecommute", "time_choice", "tours", "tour_destination", "transit_pass_ownership", "trips", "trip_destination", "workbased_subtour_generation", "workbased_subtour_mode", "work_location", "work_tour_mode", "work_trip_mode"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "../../../../inputs/base_year/survey"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to6": 5, "6to7": 6, "7to8": 7, "8to9": 8, "9to10": 9, "10to14": 10, "14to15": 14, "15to16": 15, "16to17": 16, "17to18": 17, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "base_year_2023_final", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/rtp_2026_2050", "abm_model": "daysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_daysim": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": True, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}

---
title: "Congestion"
date: today
---

In [2]:
import pandas as pd
from pathlib import Path
import util

pd.set_option('display.float_format', '{:,.1f}'.format)

## Congestion Levels by County

Congestion levels are defined by the ratio of congested speed to posted speed limits:

- Minimal: Ratio > 0.70
- Moderate: Ratio > 0.50 and <=0.70
- Heavy: > 0.25 and <= 0.50
- Severe: Ratio <= 0.25

AM (7-8)

In [3]:
# # gdf = gpd.read_file(r'../../../inputs/scenario/networks/shapefiles/AM/AM_edges.shp')
# gdf = gpd.read_file(Path(summary_config['sc_run_path'], 'inputs/scenario/networks/shapefiles/AM/AM_edges.shp'))
# gdf.crs = 'EPSG:2285'

# df = process_network_summary()
# # NOTE: for visualization, do not show connectors
# df = df[df['data3'] != 5]
# gdf = gdf.merge(df[df['tod'] == '7to8'][['ij','congestion_index','congestion_category']], left_on='link_id', right_on='ij', how='left')
# gdf['congestion_category'] = gdf['congestion_category'].fillna('Light')
# color_mapping = {'Light': 'grey','Moderate': 'orange','Heavy': 'red','Severe':'black'}
# gdf.plot(color=gdf["congestion_category"].map(color_mapping), alpha=0.3, linewidth=gdf['lanes'], figsize=(20,20))

In [4]:
df = util.process_network_summary()
df = df[df['county']!='Outside Region']


:::{.panel-tabset}
### AM Peak (7 to 8 AM)

VMT

In [5]:
pd.options.display.float_format = '{:0,.0f}'.format
df_am = df[df['tod'] == '7to8']
_df = df_am.pivot_table(index='congestion_category',columns='county',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df['Region'] = _df.sum(axis=1)
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

# _df

                    King  Kitsap  Pierce  Snohomish    Region
Light          2,084,073 283,512 999,260    892,564 4,259,409
Moderate         572,092   6,583 176,000    148,345   903,021
Heavy            515,072   9,394  62,903     87,338   674,707
Severe            54,228     671   4,053      5,772    64,724
Heavy + Severe   569,300  10,065  66,955     93,110   739,431

----
Share of VMT

In [6]:

pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                King  Kitsap  Pierce  Snohomish  Region
Light          54.9%   91.4%   76.3%      72.7%   64.1%
Moderate       15.1%    2.1%   13.4%      12.1%   13.6%
Heavy          13.6%    3.0%    4.8%       7.1%   10.2%
Severe          1.4%    0.2%    0.3%       0.5%    1.0%
Heavy + Severe 15.0%    3.2%    5.1%       7.6%   11.1%

### PM Peak (5 to 6 PM)

VMT

In [7]:
pd.options.display.float_format = '{:0,.0f}'.format
df_pm = df[df['tod'] == '17to18']
_df = df_pm.pivot_table(index='congestion_category',columns='county',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df['Region'] = _df.sum(axis=1)
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

                    King  Kitsap    Pierce  Snohomish    Region
Light          2,448,471 319,793 1,149,538  1,002,557 4,920,359
Moderate         588,251   6,167   156,975    168,305   919,698
Heavy            377,193   9,202    62,261     63,763   512,419
Severe            38,720     760     4,913      5,098    49,490
Heavy + Severe   415,913   9,962    67,174     68,861   561,910

----
Share of VMT

In [8]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                King  Kitsap  Pierce  Snohomish  Region
Light          63.3%   92.5%   79.8%      76.6%   70.7%
Moderate       15.2%    1.8%   10.9%      12.9%   13.2%
Heavy           9.8%    2.7%    4.3%       4.9%    7.4%
Severe          1.0%    0.2%    0.3%       0.4%    0.7%
Heavy + Severe 10.8%    2.9%    4.7%       5.3%    8.1%

:::

## Congestion by Road Type


:::{.panel-tabset}
### AM Peak (7 to 8 AM)

VMT

In [9]:
pd.options.display.float_format = '{:0,.0f}'.format
df_am = df[df['tod'] == '7to8']
_df = df_am.pivot_table(index='congestion_category',columns='facility_type',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

                Arterial  Connector   Highway  Other
Light          2,111,514    324,491 1,823,082    322
Moderate         323,471        NaN   579,510     39
Heavy            187,917        NaN   486,789      0
Severe            31,860        NaN    32,864      0
Heavy + Severe   219,777          0   519,653      0

----
Share of VMT

In [10]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                Arterial  Connector  Highway  Other
Light              73.5%     100.0%    53.0%  89.2%
Moderate           11.3%        NaN    16.8%  10.8%
Heavy               6.5%        NaN    14.1%   0.0%
Severe              1.1%        NaN     1.0%   0.0%
Heavy + Severe      7.6%       0.0%    15.1%   0.0%

### PM Peak (5 to 6 PM)

VMT

In [11]:

pd.options.display.float_format = '{:0,.0f}'.format
df_pm = df[df['tod'] == '17to18']
_df = df_pm.pivot_table(index='congestion_category',columns='facility_type',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

                Arterial  Connector   Highway  Other
Light          2,433,821    440,581 2,045,548    409
Moderate         330,114        NaN   589,583      0
Heavy            188,422        NaN   323,991      6
Severe            31,946        NaN    17,545      0
Heavy + Severe   220,368          0   341,536      6

----
Share of VMT

In [12]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                Arterial  Connector  Highway  Other
Light              75.9%     100.0%    61.6%  97.4%
Moderate           10.3%        NaN    17.8%   0.0%
Heavy               5.9%        NaN     9.8%   1.3%
Severe              1.0%        NaN     0.5%   0.0%
Heavy + Severe      6.9%       0.0%    10.3%   1.3%

:::

In [13]:
# _df = df_am.pivot_table(index='congestion_category',columns='facility_type',
#                aggfunc='sum',values='length')
pd.options.display.float_format = '{:0,.0f}'.format
df_pm['length'].sum()

15259.245737118326

## Miles of Roadway withy Heavy Congestion

In [14]:
print(f"Total Miles of Roadway: {int(df_am['length'].sum())}")

Total Miles of Roadway: 15259

In [15]:
congested_len = df_am[df_am['congestion_category'].isin(['Heavy','Severe'])]['length'].sum()
print(f"Total Miles of Roadway: {int(congested_len)}")

Total Miles of Roadway: 459

In [16]:
print(f"Share Congested: {congested_len/df_pm['length'].sum():.1%}")

Share Congested: 3.0%

## Corridor Travel Time

:::{.panel-tabset}
### AM Peak (7 to 8 AM)

In [17]:
pd.options.display.float_format = '{:0,.1f}'.format

df = pd.read_csv(util.output_path / 'validation/corridor_speeds.csv')

# For each Corridor_Descrption, define as AM or pm beak by finding which direction has max value
df = df[df['tod'].isin(['7to8','17to18']) & (df['Corridor_Number'] <= 20)]

# Corridors are grouped so that directions are [1,2], [3,4]
for i in range(1,21):
# for i in range(7,8):
    _df = df[df['Corridor_Number'] == i]
#     print(_df)
    peak_time = _df.sort_values('auto_time').iloc[-1]['tod']
    df.loc[df['Corridor_Number']==i, 'peak'] = peak_time
    
df.rename(columns={'Corridor_Description': 'Corridor', 'auto_time':'Auto Travel Time (min.)'}, inplace=True)
df[(df['peak'] == '7to8') & (df['tod'] == '7to8')][['Corridor','Auto Travel Time (min.)']]

                             Corridor  Auto Travel Time (min.)
15            Everett to Seattle - SB                     59.6
24             Tacoma to Seattle - NB                     65.1
51          Lynnwood to Bellevue - SB                     36.7
60           Tukwila to Bellevue - NB                     30.4
78              Auburn to Renton - NB                     24.9
96            Redmond to Seattle - WB                     29.1
114          Redmond to Bellevue - WB                     12.5
132         Issaquah to Bellevue - WB                     13.9
159  Bellevue to Seattle via 520 - EB                     23.5
168   Bellevue to Seattle via 90 - WB                     26.5

### PM Peak (17 to 18 PM)

In [18]:
df[(df['peak'] == '17to18') & (df['tod'] == '17to18')][['Corridor','Auto Travel Time (min.)']]

                             Corridor  Auto Travel Time (min.)
2             Seattle to Everett - NB                     52.6
29             Seattle to Tacoma - SB                     56.4
38          Bellevue to Lynnwood - NB                     31.5
65           Bellevue to Tukwila - SB                     27.5
83              Renton to Auburn - SB                     21.4
101           Seattle to Redmond - EB                     24.6
119          Bellevue to Redmond - EB                     10.9
137         Bellevue to Issaquah - EB                     11.9
146  Seattle to Bellevue via 520 - WB                     18.5
173   Seattle to Bellevue via 90 - EB                     25.0

:::

## Delay

::: {.panel-tabset}
### Network Delay

In [19]:
df = util.process_network_summary()
df = df[df['county']!='Outside Region']

In [20]:
df[['total_delay','county']].groupby('county').sum()[['total_delay']]

           total_delay
county
King         149,280.5
Kitsap         2,552.9
Pierce        30,297.3
Snohomish     29,615.4

### Transit Delay

In [21]:
# Congestion on Transit Routes
df_network = util.process_network_summary()
# df = df[df['county']!='Outside Region']
# Get PM congestion only for now

tod = '17to18'
df_network_pm = df_network[df_network['tod']==tod]

df = pd.read_csv(util.output_path / 'transit/transit_segment_results.csv')
df = df[df['tod']==tod]

df = df[~df['j_node'].isnull()]
df = df.merge(df_network_pm, on=['i_node','j_node'], how='left')

In [22]:
df["delay"] = df["auto_time"] - df["freeflow_time"]
df["person_delay"] = df['segment_volume']*df['delay']

In [23]:
df_sum = df.groupby('line_id').sum()[['auto_time','freeflow_time','person_delay']]
df_sum['vehicle_delay'] = df_sum['auto_time']-df_sum['freeflow_time']

# Merge the line IDs to transit line results to get agency IDs or some other metric
df_line_results = pd.read_csv(util.output_path / 'transit/transit_line_results.csv')
df_line_results = df_line_results[df_line_results['tod']==tod]
df_sum = df_sum.merge(df_line_results, on='line_id', how='left')

In [24]:
# Compare person-delay in transit vs person-delay in vehicles on specific corridors

In [25]:
# # Total minutes of delay by agency
# df = df_sum.groupby('agency_code').sum()[['delay']]
# df.index = df.index.astype('int').astype('str').map(summary_config['agency_lookup'])
# df.index.name = 'Agency'
# df.rename(columns={'delay': 'Total Route Delay (min) at PM Peak'}, inplace=True)
# df

In [26]:
# # Ridership and Delay
# df_sum.groupby('agency_code').sum()[['person_delay']]/60

In [27]:
# # df = pd.read_csv((Path(output_path, 'transit/transit_segment_results.csv')))
# # df = df[df['tod']=='7to8']
# df_sum

:::