In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": True, "run_validation": True, "run_network_validation": True, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "daysim-validation-notebook": ["all_tour_mode", "all_trip_mode", "auto_ownership", "day_pattern", "escort_tour_mode", "escort_trip_mode", "households", "intermediate_stop_generation", "other_home_based_tour_mode", "other_home_based_trip_mode", "persons", "school_location", "school_tour_mode", "school_trip_mode", "telecommute", "time_choice", "tours", "tour_destination", "transit_pass_ownership", "trips", "trip_destination", "workbased_subtour_generation", "workbased_subtour_mode", "work_location", "work_tour_mode", "work_trip_mode"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "../../../../inputs/base_year/survey"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to6": 5, "6to7": 6, "7to8": 7, "8to9": 8, "9to10": 9, "10to14": 10, "14to15": 14, "15to16": 15, "16to17": 16, "17to18": 17, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "base_year_2023_final", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/rtp_2026_2050", "abm_model": "daysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_daysim": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": True, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}

---
title: "Household Transportation Costs"
date: today
---

- Average Annual Household Transportation Costs: Out-of-pocket expenses including tolls, parking, and transit fares

    - These costs do not include other vehicle operating and purchase costs.

    - Costs are annualized using factor of 320

In [2]:
import pandas as pd
import polars as pl
from pathlib import Path
import util

pd.set_option('display.float_format', '${:0,.0f}'.format)

In [3]:
# person data
person = pd.read_csv(util.output_path / 'agg/dash/person_cost.csv')
# household data
hh = pd.read_csv(util.output_path / 'agg/dash/hh_geog.csv')

annual_factor = util.summary_config['weekday_to_annual']
# list of equity geographies
equity_geogs = util.summary_config['equity_geogs']
not_equity_geogs = ["NOT in " + item for item in equity_geogs]

In [4]:
df_person = person.copy()
df_person['is_rgc'] = "In RGC"
df_person.loc[df_person['hh_rgc'] == 'Not in RGC', 'is_rgc'] = "Not in RGC"
# included modes
# TODO: ask what this means
df_person = df_person[(df_person['mode'].isin(['SOV','HOV2','HOV3+']) & (df_person['dorp'] == 1)) 
                      | (~df_person['mode'].isin(['SOV','HOV2','HOV3+']))]

df_hh = hh.copy()
df_hh['is_rgc'] = "In RGC"
df_hh.loc[df_hh['hh_rgc'] == 'Not in RGC', 'is_rgc'] = "Not in RGC"

In [5]:
def annual_costs(geog, map=False):
    df = df_person.groupby(geog, as_index=False)['travcost_wt'].sum().set_index(geog)
    df['hhexpfac'] = df_hh.groupby(geog)['hhexpfac'].sum()

    if map:
        df.index = df.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'}
                                )

    df.loc['Region'] = [df_person['travcost_wt'].sum(), df_hh['hhexpfac'].sum()]
    df['Average Annual Costs'] = (df['travcost_wt'] / df['hhexpfac']) * annual_factor




    return df[['Average Annual Costs']]

:::{.panel-tabset}
### County

In [6]:
df = annual_costs('hh_county')
df = df[df.index!='Outside Region']
df

           Average Annual Costs
hh_county
King                     $2,420
Kitsap                   $3,126
Pierce                   $2,784
Snohomish                $2,954
Region                   $2,636

### Regional Growth Center

In [7]:
annual_costs('is_rgc')

            Average Annual Costs
is_rgc
In RGC                      $988
Not in RGC                $2,813
Region                    $2,636

In [8]:
annual_costs('hh_rgc')

                                 Average Annual Costs
hh_rgc
Auburn                                         $1,705
Bellevue                                       $1,062
Bothell Canyon Park                            $2,498
Bremerton                                      $1,244
Burien                                         $1,766
Everett                                        $1,081
Federal Way                                    $2,026
Greater Downtown Kirkland                      $1,948
Kent                                           $1,652
Kirkland Totem Lake                            $1,882
Lakewood                                       $1,514
Lynnwood                                       $1,826
Not in RGC                                     $2,813
Puyallup Downtown                              $1,380
Puyallup South Hill                            $1,827
Redmond Downtown                               $1,512
Redmond-Overlake                               $1,689
Renton                                         $1,551
SeaTac                                         $2,075
Seattle Downtown                                 $426
Seattle First Hill/Capitol Hill                  $623
Seattle Northgate                              $1,610
Seattle South Lake Union                         $547
Seattle University District                    $1,038
Seattle Uptown                                   $795
Silverdale                                     $1,106
Tacoma Downtown                                  $988
Tacoma Mall                                    $1,217
Tukwila                                        $1,419
University Place                               $1,617
Region                                         $2,636

### Regional Geography

In [9]:
annual_costs('hh_rg_proposed')

                                   Average Annual Costs
hh_rg_proposed
Cities and Towns                                 $3,408
Core Cities                                      $2,550
High Capacity Transit Communities                $2,803
Metropolitan Cities                              $1,730
Rural Areas                                      $4,455
Urban Unincorporated Areas                       $3,210
Region                                           $2,636

### Equity Focus Areas

In [10]:
df = pd.DataFrame()
for name, col in {
    "People of Color": "hh_efa_poc",
    "Income": "hh_efa_pov200",
    "LEP": "hh_efa_lep",
    "Disability": "hh_efa_dis",
    "Older Adults": "hh_efa_older",
    "Youth": "hh_efa_youth"
}.items():
    _df = annual_costs(col, map=True)
    _df['Group'] = name
    df = pd.concat([df, _df])

df = df.reset_index()
df
df.rename(columns={'index':'EFA Type'}, inplace=True)

df[['Group', 'EFA Type', 'Average Annual Costs']]

              Group                           EFA Type  Average Annual Costs
0   People of Color             Below Regional Average                $2,867
1   People of Color             Above Regional Average                $2,356
2   People of Color  Higher Share of Equity Population                $2,371
3   People of Color                             Region                $2,636
4            Income             Below Regional Average                $2,860
5            Income             Above Regional Average                $2,429
6            Income  Higher Share of Equity Population                $2,072
7            Income                             Region                $2,636
8               LEP             Below Regional Average                $2,704
9               LEP             Above Regional Average                $2,559
10              LEP  Higher Share of Equity Population                $2,472
11              LEP                             Region                $2,636
12       Disability             Below Regional Average                $2,743
13       Disability             Above Regional Average                $2,635
14       Disability  Higher Share of Equity Population                $2,261
15       Disability                             Region                $2,636
16     Older Adults             Below Regional Average                $2,489
17     Older Adults             Above Regional Average                $2,719
18     Older Adults  Higher Share of Equity Population                $2,998
19     Older Adults                             Region                $2,636
20            Youth             Below Regional Average                $2,256
21            Youth             Above Regional Average                $3,025
22            Youth  Higher Share of Equity Population                $3,293
23            Youth                             Region                $2,636

:::