---
title: "Congestion"
date: today
---

In [1]:
import pandas as pd
from pathlib import Path
import util

pd.set_option('display.float_format', '{:,.1f}'.format)

## Congestion Levels by County

Congestion levels are defined by the ratio of congested speed to posted speed limits:

- Minimal: Ratio > 0.70
- Moderate: Ratio > 0.50 and <=0.70
- Heavy: > 0.25 and <= 0.50
- Severe: Ratio <= 0.25

AM (7-8)

In [2]:
# # gdf = gpd.read_file(r'../../../inputs/scenario/networks/shapefiles/AM/AM_edges.shp')
# gdf = gpd.read_file(Path(summary_config['sc_run_path'], 'inputs/scenario/networks/shapefiles/AM/AM_edges.shp'))
# gdf.crs = 'EPSG:2285'

# df = process_network_summary()
# # NOTE: for visualization, do not show connectors
# df = df[df['data3'] != 5]
# gdf = gdf.merge(df[df['tod'] == '7to8'][['ij','congestion_index','congestion_category']], left_on='link_id', right_on='ij', how='left')
# gdf['congestion_category'] = gdf['congestion_category'].fillna('Light')
# color_mapping = {'Light': 'grey','Moderate': 'orange','Heavy': 'red','Severe':'black'}
# gdf.plot(color=gdf["congestion_category"].map(color_mapping), alpha=0.3, linewidth=gdf['lanes'], figsize=(20,20))

In [3]:
df = util.process_network_summary()
df = df[df['county']!='Outside Region']


:::{.panel-tabset}
### AM Peak (7 to 8 AM)

VMT

In [4]:
pd.options.display.float_format = '{:0,.0f}'.format
df_am = df[df['tod'] == '7to8']
_df = df_am.pivot_table(index='congestion_category',columns='county',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df['Region'] = _df.sum(axis=1)
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

# _df

                    King  Kitsap    Pierce  Snohomish    Region
Light          2,206,437 308,709 1,044,748    978,331 4,538,226
Moderate         631,965  13,797   207,541    173,361 1,026,664
Heavy            540,471   4,464    94,888    122,028   761,851
Severe            60,814   7,716     6,050      6,856    81,436
Heavy + Severe   601,284  12,181   100,938    128,884   843,287

----
Share of VMT

In [5]:

pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                King  Kitsap  Pierce  Snohomish  Region
Light          54.6%   89.0%   71.8%      69.4%   62.6%
Moderate       15.6%    4.0%   14.3%      12.3%   14.2%
Heavy          13.4%    1.3%    6.5%       8.7%   10.5%
Severe          1.5%    2.2%    0.4%       0.5%    1.1%
Heavy + Severe 14.9%    3.5%    6.9%       9.1%   11.6%

### PM Peak (5 to 6 PM)

VMT

In [6]:
pd.options.display.float_format = '{:0,.0f}'.format
df_pm = df[df['tod'] == '17to18']
_df = df_pm.pivot_table(index='congestion_category',columns='county',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df['Region'] = _df.sum(axis=1)
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

                    King  Kitsap    Pierce  Snohomish    Region
Light          2,558,438 352,353 1,214,707  1,135,514 5,261,012
Moderate         669,301   8,306   204,036    192,329 1,073,972
Heavy            428,992  10,955    70,737     69,727   580,411
Severe            35,865     889     5,411      7,119    49,283
Heavy + Severe   464,857  11,843    76,148     76,846   629,695

----
Share of VMT

In [7]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                King  Kitsap  Pierce  Snohomish  Region
Light          61.5%   91.7%   77.3%      76.6%   69.3%
Moderate       16.1%    2.2%   13.0%      13.0%   14.1%
Heavy          10.3%    2.9%    4.5%       4.7%    7.6%
Severe          0.9%    0.2%    0.3%       0.5%    0.6%
Heavy + Severe 11.2%    3.1%    4.8%       5.2%    8.3%

:::

## Congestion by Road Type


:::{.panel-tabset}
### AM Peak (7 to 8 AM)

VMT

In [8]:
pd.options.display.float_format = '{:0,.0f}'.format
df_am = df[df['tod'] == '7to8']
_df = df_am.pivot_table(index='congestion_category',columns='facility_type',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

                Arterial  Connector   Highway  Other
Light          2,256,179    354,282 1,927,409    356
Moderate         373,987        NaN   652,638     39
Heavy            217,178        NaN   544,673      0
Severe            35,937        NaN    45,499      0
Heavy + Severe   253,115          0   590,172      0

----
Share of VMT

In [9]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                Arterial  Connector  Highway  Other
Light              71.9%     100.0%    51.3%  90.1%
Moderate           11.9%        NaN    17.4%   9.9%
Heavy               6.9%        NaN    14.5%   0.0%
Severe              1.1%        NaN     1.2%   0.0%
Heavy + Severe      8.1%       0.0%    15.7%   0.0%

### PM Peak (5 to 6 PM)

VMT

In [10]:

pd.options.display.float_format = '{:0,.0f}'.format
df_pm = df[df['tod'] == '17to18']
_df = df_pm.pivot_table(index='congestion_category',columns='facility_type',
               aggfunc='sum',values='VMT')
_df = _df.reindex(['Light','Moderate','Heavy','Severe'])
_df.index.name = None
_df.columns.name = None
_df.loc['Heavy + Severe'] = _df.loc[['Heavy','Severe']].sum(axis=0)
_df

                Arterial  Connector   Highway  Other
Light          2,608,558    481,607 2,170,357    489
Moderate         380,564        NaN   693,407      0
Heavy            217,072        NaN   363,334      6
Severe            37,545        NaN    11,738      0
Heavy + Severe   254,617          0   375,072      6

----
Share of VMT

In [11]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = _df/_df.sum(axis=0)
_df

                Arterial  Connector  Highway  Other
Light              74.6%     100.0%    60.1%  97.8%
Moderate           10.9%        NaN    19.2%   0.0%
Heavy               6.2%        NaN    10.1%   1.1%
Severe              1.1%        NaN     0.3%   0.0%
Heavy + Severe      7.3%       0.0%    10.4%   1.1%

:::

In [12]:
# _df = df_am.pivot_table(index='congestion_category',columns='facility_type',
#                aggfunc='sum',values='length')
pd.options.display.float_format = '{:0,.0f}'.format
df_pm['length'].sum()

15333.070139977994

## Miles of Roadway withy Heavy Congestion

In [13]:
print(f"Total Miles of Roadway: {int(df_am['length'].sum())}")

Total Miles of Roadway: 15333

In [14]:
congested_len = df_am[df_am['congestion_category'].isin(['Heavy','Severe'])]['length'].sum()
print(f"Total Miles of Roadway: {int(congested_len)}")

Total Miles of Roadway: 494

In [15]:
print(f"Share Congested: {congested_len/df_pm['length'].sum():.1%}")

Share Congested: 3.2%

## Corridor Travel Time

:::{.panel-tabset}
### AM Peak (7 to 8 AM)

In [16]:
pd.options.display.float_format = '{:0,.1f}'.format

df = pd.read_csv(util.output_path / 'validation/corridor_speeds.csv')

# For each Corridor_Descrption, define as AM or pm beak by finding which direction has max value
df = df[df['tod'].isin(['7to8','17to18']) & (df['Corridor_Number'] <= 20)]

# Corridors are grouped so that directions are [1,2], [3,4]
for i in range(1,21):
# for i in range(7,8):
    _df = df[df['Corridor_Number'] == i]
#     print(_df)
    peak_time = _df.sort_values('auto_time').iloc[-1]['tod']
    df.loc[df['Corridor_Number']==i, 'peak'] = peak_time
    
df.rename(columns={'Corridor_Description': 'Corridor', 'auto_time':'Auto Travel Time (min.)'}, inplace=True)
df[(df['peak'] == '7to8') & (df['tod'] == '7to8')][['Corridor','Auto Travel Time (min.)']]

                             Corridor  Auto Travel Time (min.)
15            Everett to Seattle - SB                     61.0
24             Tacoma to Seattle - NB                     67.6
51          Lynnwood to Bellevue - SB                     37.8
60           Tukwila to Bellevue - NB                     28.0
78              Auburn to Renton - NB                     26.1
96            Redmond to Seattle - WB                     28.5
114          Redmond to Bellevue - WB                     13.2
132         Issaquah to Bellevue - WB                     14.2
150  Seattle to Bellevue via 520 - WB                     16.9
159  Bellevue to Seattle via 520 - EB                     22.6
168   Bellevue to Seattle via 90 - WB                     25.1

### PM Peak (17 to 18 PM)

In [17]:
df[(df['peak'] == '17to18') & (df['tod'] == '17to18')][['Corridor','Auto Travel Time (min.)']]

                            Corridor  Auto Travel Time (min.)
2            Seattle to Everett - NB                     53.7
29            Seattle to Tacoma - SB                     57.2
38         Bellevue to Lynnwood - NB                     32.3
65          Bellevue to Tukwila - SB                     26.2
83             Renton to Auburn - SB                     22.1
101          Seattle to Redmond - EB                     22.4
119         Bellevue to Redmond - EB                     10.9
137        Bellevue to Issaquah - EB                     12.7
173  Seattle to Bellevue via 90 - EB                     22.6

:::

## Delay

::: {.panel-tabset}
### Network Delay

In [18]:
df = util.process_network_summary()
df = df[df['county']!='Outside Region']

In [19]:
df[['total_delay','county']].groupby('county').sum()[['total_delay']]

           total_delay
county
King         166,296.6
Kitsap         4,713.2
Pierce        39,824.5
Snohomish     41,122.4

### Transit Delay

In [20]:
# Congestion on Transit Routes
df_network = util.process_network_summary()
# df = df[df['county']!='Outside Region']
# Get PM congestion only for now

tod = '17to18'
df_network_pm = df_network[df_network['tod']==tod]

df = pd.read_csv(util.output_path / 'transit/transit_segment_results.csv')
df = df[df['tod']==tod]

df = df[~df['j_node'].isnull()]
df = df.merge(df_network_pm, on=['i_node','j_node'], how='left')

In [21]:
df["delay"] = df["auto_time"] - df["freeflow_time"]
df["person_delay"] = df['segment_volume']*df['delay']

In [22]:
df_sum = df.groupby('line_id').sum()[['auto_time','freeflow_time','person_delay']]
df_sum['vehicle_delay'] = df_sum['auto_time']-df_sum['freeflow_time']

# Merge the line IDs to transit line results to get agency IDs or some other metric
df_line_results = pd.read_csv(util.output_path / 'transit/transit_line_results.csv')
df_line_results = df_line_results[df_line_results['tod']==tod]
df_sum = df_sum.merge(df_line_results, on='line_id', how='left')

In [23]:
# Compare person-delay in transit vs person-delay in vehicles on specific corridors

In [24]:
# # Total minutes of delay by agency
# df = df_sum.groupby('agency_code').sum()[['delay']]
# df.index = df.index.astype('int').astype('str').map(summary_config['agency_lookup'])
# df.index.name = 'Agency'
# df.rename(columns={'delay': 'Total Route Delay (min) at PM Peak'}, inplace=True)
# df

In [25]:
# # Ridership and Delay
# df_sum.groupby('agency_code').sum()[['person_delay']]/60

In [26]:
# # df = pd.read_csv((Path(output_path, 'transit/transit_segment_results.csv')))
# # df = df[df['tod']=='7to8']
# df_sum

:::