---
title: "Transit"
date: today
---

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import polars as pl
import geopandas as gpd
import h5py
import util

%matplotlib inline
from IPython.display import display, HTML

relative_path = Path('../../../..')

pd.set_option('display.max_rows', None)
pd.options.display.float_format = '{:0,.0f}'.format

## Transit Boardings

:::{.panel-tabset}
### Agency

In [2]:

df = pd.read_csv(util.output_path / 'transit/daily_boardings_by_agency.csv',index_col=0)
df.loc['Region Total','boardings'] = df['boardings'].sum()
df = df.reset_index()
df.rename(columns={'agency_name': 'Agency', 'boardings': 'Boardings'}, inplace=True)
HTML(df.to_html(index=False))

### Service Type

In [3]:
df = pd.read_csv(util.output_path / 'transit/transit_line_results.csv',index_col=0)

transit_type_map = {
    1: 'Local Bus',
    2: 'Express Bus',
    3: 'Bus Rapid Transit',
    4: 'Streetcar',
    5: 'Commuter Rail',
    6: 'Light Rail',
    7: 'Auto Ferry',
    8: 'Passenger Ferry'
}
df['transit_type'] = df['transit_type'].map(transit_type_map)
df = df.groupby('transit_type').sum()[['boardings']]
df.loc['Total'] = df.sum(axis=0)
df = df.reset_index()
df.rename(columns={'boardings':' Boardings','transit_type':'Transit Type'}, inplace=True)
HTML(df.to_html(index=False))

### Sound Transit Modes

In [4]:
df = pd.read_csv(util.output_path / 'transit/transit_line_results.csv',index_col=0)
df = df[(df['agency_code']==6)].groupby('transit_type').sum()[['boardings']]
df.index = df.index.map({1: 'Bus', 3: 'BRT (Stride)', 5: 'Commuter Rail', 6: 'Light Rail'})
df.rename(columns={'boardings':' Boardings'}, inplace=True)

df

               Boardings
transit_type
Bus               17,318
BRT (Stride)      30,140
Commuter Rail     12,368
Light Rail       292,742

### Light Rail

:::{.panel-tabset}

#### Boardings by Station

In [5]:
# all transit stop locations
df_transit_stops = pd.read_csv(util.input_path / 'scenario/networks/transit_stops.csv', usecols = ['PSRCJunctID', 'x', 'y','light_rail'])

# Load station names
df_lr_station_names = util.read_sqlite_db("SELECT * FROM light_rail_stations_2050")

# Merge station names to df 
light_rail_stations = df_transit_stops[df_transit_stops['light_rail']==1].\
    merge(df_lr_station_names, left_on=['PSRCJunctID'], right_on=['Station Node'])

In [6]:
# Light rail boardings by station
df_boardings = pd.read_csv(util.output_path / 'transit/boardings_by_stop.csv')
df = pd.merge(df_boardings, light_rail_stations, left_on=['i_node'], right_on=['PSRCJunctID'])

df = df[['total_boardings','Station Name','PSRCJunctID']]#.drop_duplicates()

# pivot table of boardings by station 
df[['PSRCJunctID','Station Name','total_boardings']]

    PSRCJunctID                   Station Name  total_boardings
0        197649                  Husky Stadium           11,901
1        198007                       Westlake           30,553
2        198009                       Symphony           17,371
3        198011                 Pioneer Square           15,977
4        198013                 Int'l District            6,113
5        198014                   Capitol Hill           15,354
6        198015                        Stadium              535
7        198016                           SODO            5,483
8        198017                    Beacon Hill            1,355
9        198018                    Mount Baker            1,249
10       198019                  Columbia City            1,375
11       198020                        Othello            1,530
12       198021                  Rainier Beach            1,832
13       198022             Tukwila Int'l Blvd            6,429
14       198023                 SeaTac/Airport           10,333
15       198024                     Angle Lake            3,219
16       198040            Tacoma Dome Station            6,418
17       198041              S 25th St Station              558
18       198042                  Union Station              333
19       198043      Convention Center Station               97
20       198044               Commerce Station              406
21       198067    University District Station           17,446
22       198068              Roosevelt Station           14,485
23       198069              Northgate Station            9,450
24       198070              Pinehurst Station            2,629
25       198071        Shoreline South Station            8,036
26       198072        Shoreline North Station            8,942
27       198073      Mountlake Terrace Station            6,868
28       198074               Lynnwood Station           11,070
29       198082        Kent-Des Moines Station            4,357
30       198083             S 272nd St Station            2,305
31       198084            Federal Way Station            7,517
32       198085          S Federal Way Station            4,781
33       198086                   Fife Station            2,234
34       198087            East Tacoma Station            1,968
35       198090         Tacoma General Station            1,123
36       198091                6th Ave Station              902
37       198092       Hilltop District Station              225
38       198093              St Joseph Station              413
39       198101           Judkins Park Station            1,883
40       198102          Mercer Island Station            5,556
41       198103         South Bellevue Station            5,900
42       198105              East Main Station            5,553
43       198106      Bellevue Downtown Station            7,511
44       198107              Wilburton Station            1,758
45       198109        Spring District Station            1,373
46       198110                 BelRed Station            3,627
47       198111       Overlake Village Station            4,333
48       198112     Redmond Technology Station            2,122
49       198113       Marymoor Village Station              119
50       198114       Downtown Redmond Station            4,017
51       198128               Delridge Station              568
52       198129                 Avalon Station              669
53       198130  West Seattle Junction Station            1,071
54       198352          Boeing Access Station              171
55       198888                 Graham Station            1,466
56       198889          Old City Hall Station              261
57       200950               S 4th St Station              249
58       200951       Stadium District Station            1,364

#### Boardings by Line

In [7]:
# Light rail boardings by segment
df = pd.read_csv(util.output_path / 'transit/transit_line_results.csv', usecols = ['line_id','mode','description'])
df_light_rail = df[(df['mode']=="r") & (df['description']!="Streetcar-South Lake")].copy().\
    drop_duplicates()
df_light_rail['description'] = df_light_rail['description'].str[:6]
df_light_rail.rename(columns={'description':'Line'}, inplace=True)

In [8]:
# Light rail boardings by segment
df_boardings = pd.read_csv(util.output_path / 'transit/transit_segment_results.csv')

# get line and depart station names
df = df_boardings.merge(df_lr_station_names, left_on=['i_node'], right_on=['Station Node']).\
    merge(df_light_rail, on=['line_id'])

# all station boardings by line
board_station_line = df.groupby(['Line','Station Name'])['segment_boarding'].sum().reset_index()

In [9]:
board_station_line.groupby('Line')['segment_boarding'].sum().\
    reset_index().set_index('Line').\
    rename(columns={'segment_boarding':'Total Boardings'})

        Total Boardings
Line
1 Line          148,646
2 Line          133,624
3 Line            3,821
T Line            6,651

#### 1 Line Boardings

In [10]:
def get_stop_boardings(line_name):
    df = board_station_line[board_station_line['Line']==line_name]
    df2 = df.groupby('Line').sum()['segment_boarding'].reset_index()
    df2['Station Name'] = 'Total'
    return pd.concat([df2[["Line", "Station Name", "segment_boarding"]],df], ignore_index=True)

get_stop_boardings('1 Line')

      Line                 Station Name  segment_boarding
0   1 Line                        Total           148,646
1   1 Line                   Angle Lake             3,219
2   1 Line                  Beacon Hill             1,355
3   1 Line        Boeing Access Station               171
4   1 Line                 Capitol Hill             7,429
5   1 Line                Columbia City             1,375
6   1 Line          East Tacoma Station             1,968
7   1 Line          Federal Way Station             7,517
8   1 Line                 Fife Station             2,234
9   1 Line               Graham Station             1,466
10  1 Line                Husky Stadium             6,382
11  1 Line               Int'l District             2,081
12  1 Line      Kent-Des Moines Station             4,357
13  1 Line             Lynnwood Station             6,175
14  1 Line                  Mount Baker             1,249
15  1 Line    Mountlake Terrace Station             3,517
16  1 Line            Northgate Station             4,794
17  1 Line                      Othello             1,530
18  1 Line            Pinehurst Station             1,326
19  1 Line               Pioneer Square             7,026
20  1 Line                Rainier Beach             1,832
21  1 Line            Roosevelt Station             7,397
22  1 Line           S 272nd St Station             2,305
23  1 Line        S Federal Way Station             4,781
24  1 Line                         SODO             3,970
25  1 Line               SeaTac/Airport            10,333
26  1 Line      Shoreline North Station             4,884
27  1 Line      Shoreline South Station             4,135
28  1 Line                      Stadium               535
29  1 Line                     Symphony             8,029
30  1 Line          Tacoma Dome Station             5,697
31  1 Line           Tukwila Int'l Blvd             6,429
32  1 Line  University District Station             8,995
33  1 Line                     Westlake            14,152

#### 2 Line Boardings

In [11]:
get_stop_boardings('2 Line')

      Line                 Station Name  segment_boarding
0   2 Line                        Total           133,624
1   2 Line               BelRed Station             3,627
2   2 Line    Bellevue Downtown Station             7,511
3   2 Line                 Capitol Hill             7,925
4   2 Line     Downtown Redmond Station             4,017
5   2 Line            East Main Station             5,553
6   2 Line                Husky Stadium             5,519
7   2 Line               Int'l District             4,032
8   2 Line         Judkins Park Station             1,883
9   2 Line             Lynnwood Station             4,895
10  2 Line     Marymoor Village Station               119
11  2 Line        Mercer Island Station             5,556
12  2 Line    Mountlake Terrace Station             3,351
13  2 Line            Northgate Station             4,656
14  2 Line     Overlake Village Station             4,333
15  2 Line            Pinehurst Station             1,302
16  2 Line               Pioneer Square             8,951
17  2 Line   Redmond Technology Station             2,122
18  2 Line            Roosevelt Station             7,088
19  2 Line      Shoreline North Station             4,058
20  2 Line      Shoreline South Station             3,901
21  2 Line       South Bellevue Station             5,900
22  2 Line      Spring District Station             1,373
23  2 Line                     Symphony             9,342
24  2 Line  University District Station             8,451
25  2 Line                     Westlake            16,401
26  2 Line            Wilburton Station             1,758

#### 3 Line Boardings

In [12]:
get_stop_boardings('3 Line')

     Line                   Station Name  segment_boarding
0  3 Line                          Total             3,821
1  3 Line                 Avalon Station               669
2  3 Line               Delridge Station               568
3  3 Line                           SODO             1,513
4  3 Line  West Seattle Junction Station             1,071

#### 4 Line Boardings

In [13]:
get_stop_boardings('4 Line')

Empty DataFrame
Columns: [Line, Station Name, segment_boarding]
Index: []

#### T Line Boardings

In [14]:
get_stop_boardings('T Line')

      Line               Station Name  segment_boarding
0   T Line                      Total             6,651
1   T Line            6th Ave Station               902
2   T Line           Commerce Station               406
3   T Line  Convention Center Station                97
4   T Line   Hilltop District Station               225
5   T Line      Old City Hall Station               261
6   T Line          S 25th St Station               558
7   T Line           S 4th St Station               249
8   T Line          St Joseph Station               413
9   T Line   Stadium District Station             1,364
10  T Line        Tacoma Dome Station               720
11  T Line     Tacoma General Station             1,123
12  T Line              Union Station               333

:::

### Trips by Submode

In [15]:
df = pd.read_csv(util.output_path / 'transit/total_transit_trips.csv',index_col=0)
df.rename(index={'commuter_rail': 'Commuter Rail',
                'litrat': 'Light Rail',
                'ferry': 'Auto Ferry',
                'passenger_ferry': 'Passenger Ferry',
                'trnst': 'Bus'}, inplace=True)
df.columns = ['Total Trips']
df.loc['Total'] = df.sum(axis=0)
df.reset_index(inplace=True)
df.rename(columns={'index': 'Transit Type'}, inplace=True)
HTML(df.to_html(index=False))

:::

## Households Near HCT

In [16]:
# List of Stations
# Load transit stops file

#"The definition we have been using for the RTP is BRT, LRT, Commuter Rail, StreetCar and Ferry."
df = pd.read_csv(util.input_path / 'scenario/networks/transit_stops.csv')
# Streetcar is coded as light rail
df['hct'] = 0
df.loc[df[['commuter_rail','light_rail','ferry','brt']].sum(axis=1) > 0,'hct'] = 1
df_hct = df[df['hct'] == 1]

# Map of Stations
# Load as a geodataframe
gdf_hct = gpd.GeoDataFrame(
    df_hct, geometry=gpd.points_from_xy(df_hct.x, df_hct.y))

gdf_hct.crs = 'EPSG:2285'

In [17]:
df_lu = util.get_parcels_urbansim_data(inc_geog=True)
parcel_geog = util.get_parcel_geog()

# Load as a geodataframe
gdf_lu = gpd.GeoDataFrame(
    df_lu, geometry=gpd.points_from_xy(df_lu.xcoord_p, df_lu.ycoord_p))

gdf_lu.crs = 'EPSG:2285'

In [18]:
# Add a field that defines whether a parcel is inside (1) or outside (0) any RGC
df_lu['RGC_binary'] = 0
df_lu.loc[df_lu['GrowthCenterName'] != 'Not in RGC', 'RGC_binary'] = 1

In [19]:
def calculate_buffer(gdf_lu, _gdf_hct, distance):
    
    # Buffer the HCT station gdf
    _gdf_hct['geometry'] = _gdf_hct.buffer(distance)

    gdf_intersect = gpd.overlay(_gdf_hct, gdf_lu, how="intersection", keep_geom_type=False)
    df = df_lu[df_lu['parcelid'].isin(gdf_intersect['parcelid'].unique())]
    
    return df, gdf_intersect

def aggregate_parcels(df, col_dict, sum_field):
    results_df = pd.DataFrame()
    for col, name in col_dict.items():
        _df = df[[col,sum_field]].groupby(col).sum()[[sum_field]]
        _df['group'] = name
        results_df = pd.concat([results_df,_df])
    results_df = results_df.reset_index()
    
    return results_df

In [20]:
df_025, gdf_025 = calculate_buffer(gdf_lu, gdf_hct.copy(), distance=5280.0/4)

In [21]:
df_050, gdf_050 = calculate_buffer(gdf_lu, gdf_hct.copy(), distance=5280.0/2)

In [22]:
pd.options.display.float_format = '{:0,.0f}'.format
col_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability',
           'rg_proposed': 'Regional Geography',
            'CountyName': 'County',
            'GrowthCenterName': 'Regional Growth Center',
            'RGC_binary': 'RGC Binary',
            'Region': 'Region'
           }

hct_hh_df = pd.DataFrame()
df_025 = df_025.copy()
df_025['Region'] = 1
df = aggregate_parcels(df_025, col_dict, 'hh_p')
df['distance'] = 0.25
hct_hh_df = pd.concat([hct_hh_df,df])
df_050 = df_050.copy()
df_050['Region'] = 1
df = aggregate_parcels(df_050, col_dict, 'hh_p')
df['distance'] = 0.50
hct_hh_df = pd.concat([hct_hh_df,df])

In [23]:
pd.options.display.float_format = '{:0,.0f}'.format

:::{.panel-tabset}

### Region

In [24]:

df = hct_hh_df[hct_hh_df['group'] == 'Region']
df = df.rename(columns={'hh_p': 'Total'}).copy()
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Region'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df = df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'})

df['% of Households (1/4 Mile)'] = df['1/4 Mile']/df_lu['hh_p'].sum()
df['% of Households (1/2 Mile)'] = df['1/2 Mile']/df_lu['hh_p'].sum()

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### County

In [25]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'County'].copy()
df = df.rename(columns={'hh_p': 'Total'}).copy()
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'County'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

_df = df.merge(df_lu[['CountyName','hh_p']].groupby('CountyName').sum()[['hh_p']].reset_index(),left_on='County', right_on='CountyName')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['County', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='County')

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Growth Center

In [26]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'RGC Binary'].copy()
df.rename(columns={'hh_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'RGC Binary'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)


_df = df.merge(df_lu[['RGC_binary','hh_p']].groupby('RGC_binary').sum()[['hh_p']].reset_index(),left_on='RGC Binary', 
               right_on='RGC_binary')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['RGC Binary', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='RGC Binary')
df['RGC Designation'] = df['RGC Binary'].map({0: 'Outside RGC', 1: 'Inside RGC'})
df = df[['RGC Designation','1/4 Mile','1/2 Mile','% of Households (1/4 Mile)', '% of Households (1/2 Mile)']]
output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

In [27]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'Regional Growth Center'].copy()
df.rename(columns={'hh_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Growth Center'
# Ensure all RGCs are included, even those that have no HCT access
for center in parcel_geog['GrowthCenterName'].unique():
    if center not in df.index:
        df.loc[center] = 0

df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

# Calcualte the percent of households in this geography within 1/4 and 1/2 mile
_df = df.merge(df_lu[['GrowthCenterName','hh_p']].groupby('GrowthCenterName').sum()[['hh_p']].reset_index(),left_on='Regional Growth Center', 
               right_on='GrowthCenterName')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['Regional Growth Center', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='Regional Growth Center')

df = df.sort_values('Regional Growth Center')

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Geography

In [28]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'Regional Geography'].copy()
df.rename(columns={'hh_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Geography'
df.reset_index(inplace=True)

df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
HTML(df.to_html(index=False))

_df = df.merge(df_lu[['rg_proposed','hh_p']].groupby('rg_proposed').sum()[['hh_p']].reset_index(),left_on='Regional Geography', 
               right_on='rg_proposed')
_df['% of Households (1/4 Mile)'] = _df['1/4 Mile']/_df['hh_p']
_df['% of Households (1/2 Mile)'] = _df['1/2 Mile']/_df['hh_p']

df = df.merge(_df[['Regional Geography', '% of Households (1/4 Mile)', '% of Households (1/2 Mile)']], 
              on='Regional Geography')

output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Equity Geography

In [29]:
pd.options.display.float_format = '{:0,.2f}'.format
# df = hct_hh_df.copy()
# df = df[df['index'] == 1]
# df.rename(columns={'hh_p': 'Total'}, inplace=True)
# df.drop('index', axis=1, inplace=True)
# df = df.pivot_table(index='group', columns='distance', values='Total', aggfunc='sum')
# df[0.25] = df[0.25].astype('float32')
# df[0.5] = df[0.5].astype('float32')
# df.index.name = 'Equity Geography'
# df = df.reset_index()
# df = df.rename_axis(None, axis=1)
# df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

In [30]:
pd.options.display.float_format = '{:0,.1f}'.format

equity_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability'}

df = hct_hh_df[hct_hh_df['group'].isin(equity_dict.values())].copy()
df['EFA Type'] = df['index'].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

df = df.pivot_table(index=['group','EFA Type'], columns='distance', values='hh_p', aggfunc='sum').reset_index()

# Merge with total households to get shares of group
efa_pop_tot = df_lu[equity_dict.keys()].sum().to_dict()

for lu_col, label in equity_dict.items():
    df.loc[df['group'] == label, "Total Pop"] = efa_pop_tot[lu_col]
df['% of Households (1/4 Mile)'] = df[0.25]/df['Total Pop']
df['% of Households (1/2 Mile)'] = df[0.5]/df['Total Pop']

df.rename(columns={'group': 'Group', 0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df = df.rename_axis(None, axis=1)
df.drop('Total Pop', inplace=True, axis=1)
output = df.to_html(formatters={
    '% of Households (1/4 Mile)': '{:0,.1%}'.format,
    '% of Households (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

:::

## Jobs Near HCT

In [31]:
pd.options.display.float_format = '{:0,.0f}'.format
col_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability',
           'rg_proposed': 'Regional Geography',
            'CountyName': 'County',
            'GrowthCenterName': 'Regional Growth Center',
            'RGC_binary': 'RGC Binary',
            'Region': 'Region'
           }

hct_hh_df = pd.DataFrame()
df_025['Region'] = 1
df = aggregate_parcels(df_025, col_dict, 'emptot_p')
df['distance'] = 0.25
hct_hh_df = pd.concat([hct_hh_df,df])
df_050['Region'] = 1
df = aggregate_parcels(df_050, col_dict, 'emptot_p')
df['distance'] = 0.50
hct_hh_df = pd.concat([hct_hh_df,df])


:::{.panel-tabset}
### Region

In [32]:

df = hct_hh_df[hct_hh_df['group'] == 'Region'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Region'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

df['% of Jobs (1/4 Mile)'] = df['1/4 Mile']/df_lu['emptot_p'].sum()
df['% of Jobs (1/2 Mile)'] = df['1/2 Mile']/df_lu['emptot_p'].sum()

output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### County

In [33]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'County'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'County'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)

_df = df.merge(df_lu[['CountyName','emptot_p']].groupby('CountyName').sum()[['emptot_p']].reset_index(),left_on='County', right_on='CountyName')
_df['% of Jobs (1/4 Mile)'] = _df['1/4 Mile']/_df['emptot_p']
_df['% of Jobs (1/2 Mile)'] = _df['1/2 Mile']/_df['emptot_p']

df = df.merge(_df[['County', '% of Jobs (1/4 Mile)', '% of Jobs (1/2 Mile)']], 
              on='County')

output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Growth Center

In [34]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'RGC Binary'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'RGC Binary'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)


_df = df.merge(df_lu[['RGC_binary','emptot_p']].groupby('RGC_binary').sum()[['emptot_p']].reset_index(),left_on='RGC Binary', 
               right_on='RGC_binary')
_df['% of Jobs (1/4 Mile)'] = _df['1/4 Mile']/_df['emptot_p']
_df['% of Jobs (1/2 Mile)'] = _df['1/2 Mile']/_df['emptot_p']

df = df.merge(_df[['RGC Binary', '% of Jobs (1/4 Mile)', '% of Jobs (1/2 Mile)']], 
              on='RGC Binary')
df['RGC Designation'] = df['RGC Binary'].map({0: 'Outside RGC', 1: 'Inside RGC'})
df = df[['RGC Designation','1/4 Mile','1/2 Mile','% of Jobs (1/4 Mile)', '% of Jobs (1/2 Mile)']]
output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

In [35]:
pd.options.display.float_format = '{:0,.0f}'.format
df = hct_hh_df[hct_hh_df['group'] == 'Regional Growth Center'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Growth Center'
# Ensure all RGCs are included, even those that have no HCT access
for center in parcel_geog['GrowthCenterName'].unique():
    if center not in df.index:
        df.loc[center] = 0
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df['% of Total Jobs (1/4 Mile)'] = df['1/4 Mile']/df_lu['emptot_p'].sum()
df['% of Total Jobs (1/2 Mile)'] = df['1/2 Mile']/df_lu['emptot_p'].sum()

output = df.to_html(formatters={
    '% of Total Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Total Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Regional Geography

In [36]:
df = hct_hh_df[hct_hh_df['group'] == 'Regional Geography'].copy()
df.rename(columns={'emptot_p': 'Total'}, inplace=True)
df = df.pivot_table(index='index', columns='distance', values='Total', aggfunc='sum')
df = df.fillna(0)
df[0.25] = df[0.25].astype('float32')
df[0.5] = df[0.5].astype('float32')
df.index.name = 'Regional Geography'
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.rename(columns={0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df['% of Total Jobs (1/4 Mile)'] = df['1/4 Mile']/df_lu['emptot_p'].sum()
df['% of Total Jobs (1/2 Mile)'] = df['1/2 Mile']/df_lu['emptot_p'].sum()

output = df.to_html(formatters={
    '% of Total Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Total Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Equity Geography

In [37]:
pd.options.display.float_format = '{:0,.0f}'.format

equity_dict = {'equity_focus_areas_2023__efa_poc': 'People of Color',
                      'equity_focus_areas_2023__efa_pov200': 'Poverty',
                        'equity_focus_areas_2023__efa_lep': 'LEP',
                      'equity_focus_areas_2023__efa_older': 'Older',
                      'equity_focus_areas_2023__efa_youth': 'Youth',
            'equity_focus_areas_2023__efa_dis': 'Disability'}

df = hct_hh_df[hct_hh_df['group'].isin(equity_dict.values())].copy()
df['EFA Type'] = df['index'].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

df = df.pivot_table(index=['group','EFA Type'], columns='distance', values='emptot_p', aggfunc='sum').reset_index()

# Merge with total households to get shares of group
efa_pop_tot = df_lu[equity_dict.keys()].sum().to_dict()

df[0.25] = df[0.25].astype("float")
df[0.50] = df[0.50].astype("float")

for lu_col, label in equity_dict.items():
    df.loc[df['group'] == label, "Total Jobs"] = efa_pop_tot[lu_col]
df['% of Households (1/4 Mile)'] = df[0.25]/df['Total Jobs']
df['% of Households (1/2 Mile)'] = df[0.5]/df['Total Jobs']


df.rename(columns={'group': 'Group', 0.25: '1/4 Mile', 0.5: '1/2 Mile'}, inplace=True)
df = df.rename_axis(None, axis=1)
df.drop('Total Jobs', inplace=True, axis=1)
output = df.to_html(formatters={
    '% of Jobs (1/4 Mile)': '{:0,.1%}'.format,
    '% of Jobs (1/2 Mile)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

:::

## Transit Access Mode
Percent of Transit Trips Accessed by Walking

:::{.panel-tabset}
### Region

In [38]:
pd.options.display.float_format = '{:0,.1%}'.format
df = pd.read_csv(util.output_path / 'agg/dash/trip_mode_by_tour_mode.csv')
_df = df.copy()
pnr_transit_trips = _df[(_df['tmodetp'] == 'Park') & (_df['mode'] == 'Transit')]['trexpfac'].sum()
walk_transit_trips = _df[(_df['tmodetp'] == 'Transit') & (_df['mode'] == 'Transit')]['trexpfac'].sum()
reg_access = (walk_transit_trips/(walk_transit_trips+pnr_transit_trips))
pd.DataFrame([reg_access], columns=['% Transit trips Accessed by Walking'], index=['Region'])

        % Transit trips Accessed by Walking
Region                                95.1%

### Equity Geographies

In [39]:
pd.options.display.float_format = '{:0,.1%}'.format
_df = df.copy()
results_df = pd.DataFrame()
list_50 = ['hh_racial','hh_poverty']
# for col in ['hh_disability','hh_elderly','hh_english','hh_poverty','hh_racial','hh_youth']:
for col in util.summary_config["hh_equity_geogs"]:
    pnr_transit_trips = _df[(_df[col] == 1) & 
                            (_df['tmodetp'] == 'Park') &
                            (_df['mode'] == 'Transit')]['trexpfac'].sum()
    walk_transit_trips = _df[(_df[col] == 1) & 
                                (_df['tmodetp'] == 'Transit') & 
                                (_df['mode'] == 'Transit')]['trexpfac'].sum()
    if (pnr_transit_trips > 0) & (walk_transit_trips > 0):
        results_df.loc[col,'% Transit Trips Accessed by Walking'] = walk_transit_trips/(walk_transit_trips+pnr_transit_trips)
# results_df.rename(columns={'_reg':'> Regional Average', '_50': '> 50%'}, inplace=True)
results_df

               % Transit Trips Accessed by Walking
hh_efa_dis                                   95.6%
hh_efa_older                                 94.6%
hh_efa_lep                                   95.1%
hh_efa_pov200                                95.5%
hh_efa_poc                                   95.2%
hh_efa_youth                                 93.2%

:::

## Transit Equity

### Trip purpose by transit mode type

In [40]:
myh5 = h5py.File(util.input_path / 'scenario/landuse/hh_and_persons.h5', 'r')
person = pd.read_csv(util.output_path / 'daysim/_person.tsv', sep='\t')
df_trip = pd.read_csv(util.output_path / 'daysim/_trip.tsv', sep='\t')
df_hh = pd.read_csv(util.output_path / 'daysim/_household.tsv', sep='\t')

In [41]:
# Create a DataFrame from the h5 file
df_person = pd.DataFrame()
for col in ['hhno','pno','prace']:
    df_person[col] = myh5['Person'][col][:]

df_trip = df_trip.merge(df_person[['hhno','pno','prace']], on=['hhno','pno'], how='left')

In [42]:
# Create group of work, school, and all other purposes
df_trip['Purpose Type'] = 'Other'
df_trip.loc[df_trip['dpurp']==0, 'Purpose Type'] = 'Home'
df_trip.loc[df_trip['dpurp']==1, 'Purpose Type'] = 'Work'
df_trip.loc[df_trip['dpurp']==2, 'Purpose Type'] = 'School'

# Rename path types
df_trip.loc[df_trip['pathtype']==1, 'Path Type'] = 'Drive'
df_trip.loc[df_trip['pathtype']==3, 'Path Type'] = 'Bus'
df_trip.loc[df_trip['pathtype']==4, 'Path Type'] = 'Light Rail'
df_trip.loc[df_trip['pathtype']==5, 'Path Type'] = 'Ferry 1'
df_trip.loc[df_trip['pathtype']==6, 'Path Type'] = 'Commuter Rail'
df_trip.loc[df_trip['pathtype']==7, 'Path Type'] = 'Ferry 2'

df = pd.pivot_table(df_trip[(df_trip['dpurp']!=0) & (~df_trip['pathtype'].isin([0,'Drive']))], values='trexpfac', index='Path Type', columns='Purpose Type', aggfunc='sum')

df['Total'] = df.sum(axis=1)
for row in df.index:
    for col in ['Work','School','Other']:
        df.loc[row, col + ' %'] = df.loc[row, col] / df.loc[row, 'Total']

df[['Work %','School %','Other %']] = df[['Work %','School %','Other %']].map("{:,.1%}".format)
df[['Work %','School %','Other %']]

Purpose Type  Work % School % Other %
Path Type
Bus            14.8%    13.3%   71.9%
Commuter Rail  55.3%     2.2%   42.5%
Drive          20.3%     5.8%   73.9%
Ferry 1        45.2%    12.7%   42.1%
Ferry 2        57.2%     4.7%   38.1%
Light Rail     32.4%    12.4%   55.2%

In [43]:

race_dict = {
    '1': 'White alone',
    '2': 'Black or African American alone',
    '3': 'American Indian alone',
    '4': 'Alaska Native alone',
    '5': 'American Indian and Alaska Native tribes specified',
    '6': 'Asian alone',
    '7': 'Native Hawaiian and Other Pacific Islander alone',
    '8': 'Some Other Race alone',
    '9': 'Two or More Races'
}


df_trip['Race'] = df_trip['prace'].astype('int').astype('str').map(race_dict)

### Transit type distribution by race of rider

In [44]:
# Submode Ridership by race
df = pd.pivot_table(df_trip[(df_trip['pathtype']!="Drive")], values='trexpfac', index='Path Type', columns='Race', aggfunc="sum")
race_cols = ['White alone','Black or African American alone','American Indian alone',
             'Alaska Native alone','American Indian and Alaska Native tribes specified','Asian alone',
             'Native Hawaiian and Other Pacific Islander alone','Some Other Race alone','Two or More Races']
# Calculate shares of total by Race for each Path Type
df['Total'] = df.sum(axis=1)
df = df.astype('float')
for row in df.index:
    for col in race_cols:
        df.loc[row, col] = df.loc[row, col] / df.loc[row, 'Total']
df[race_cols] = df[race_cols].map("{:,.1%}".format)
df[race_cols]

Race,White alone,Black or African American alone,American Indian alone,Alaska Native alone,American Indian and Alaska Native tribes specified,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some Other Race alone,Two or More Races
Path Type,,,,,,,,,
Bus,60.7%,7.4%,0.6%,0.1%,0.1%,17.3%,0.7%,4.2%,8.9%
Commuter Rail,62.6%,8.5%,0.6%,0.1%,0.1%,11.3%,1.8%,5.6%,9.3%
Drive,64.9%,5.6%,0.6%,0.1%,0.1%,14.5%,0.9%,4.3%,8.9%
Ferry 1,77.6%,2.4%,0.5%,0.1%,0.2%,5.9%,1.3%,3.2%,8.9%
Ferry 2,77.1%,2.4%,0.6%,0.1%,0.1%,8.6%,0.6%,3.1%,7.4%
Light Rail,60.1%,7.1%,0.5%,0.1%,0.1%,18.8%,0.7%,4.1%,8.5%

In [45]:
df_trip = df_trip.merge(df_hh[['hhno','hhincome']], on=['hhno'], how='left')

### Income distribution by household income of rider

In [46]:
# Create bins for hhincome
bins = [0, 20000, 40000, 60000, 80000, 100000, 120000, 140000, 160000, 180000, 200000, np.inf]
labels = ['<20k', '20-40k', '40-60k', '60-80k', '80-100k', '100-120k', '120-140k', '140-160k', '160-180k', '180-200k', '>200k']
df_trip['Income Bin'] = pd.cut(df_trip['hhincome'], bins=bins, labels=labels, right=False)
df_trip['Income Bin'] = df_trip['Income Bin'].astype('str')

# Transit Submodes by Income
df = pd.pivot_table(df_trip[(df_trip['Path Type']!="Drive")], values='trexpfac', index='Path Type', columns='Income Bin', aggfunc="sum")

# display labels with no significant figs
df[labels] = df[labels].map("{:0,.0f}".format)
df[labels]

Income Bin,<20k,20-40k,40-60k,60-80k,80-100k,100-120k,120-140k,140-160k,160-180k,180-200k,>200k
Path Type,,,,,,,,,,,
Bus,"45,680","41,266","36,685","32,227","31,331","25,234","23,381","20,642","17,289","15,232","83,734"
Commuter Rail,275,628,"1,143","1,344","1,571","1,477","1,289","1,137",828,807,"2,883"
Ferry 1,302,452,480,566,525,490,521,439,286,237,"1,168"
Ferry 2,333,738,"1,333","1,688","1,862","1,704","1,706","1,644","1,334","1,079","7,038"
Light Rail,"21,571","21,551","22,627","22,021","22,977","19,597","18,511","16,639","13,955","12,621","74,549"

In [47]:
pd.pivot_table(
    df_trip[df_trip['Path Type'] != "Drive"],
    values='hhincome',
    index='Path Type',
    aggfunc="median"
).astype(int).map(lambda x: "${:,.0f}".format(x))

               hhincome
Path Type
Bus             $99,537
Commuter Rail  $124,419
Ferry 1        $117,241
Ferry 2        $150,425
Light Rail     $122,928