---
title: "Walk and Bike"
date: today
---

In [1]:
import pandas as pd
import polars as pl
import util
from pathlib import Path

pd.set_option('display.float_format', '{:,.0f}'.format)

## Average Miles Walking and Biking per Day by Resident

In [2]:
# trip,person,vmt data
person_trips = pd.read_csv(util.output_path / 'agg/dash/person_trips.csv')
person = pd.read_csv(util.output_path / 'agg/dash/person_geog.csv')
vmt = pd.read_csv(util.output_path / 'agg/dash/person_vmt.csv')

# list of equity geographies
equity_geogs = util.summary_config['hh_equity_geogs']

# TRIPS
df_trip = person_trips.copy()

# add home RGC
df_trip = util.get_is_rgc(df_trip, 'hh_rgc')
# add trip type
df_trip.loc[df_trip['dpurp'] != 'Work', 'trip_type'] = 'Non-Work'
df_trip.loc[df_trip['dpurp'] == 'Work', 'trip_type'] = 'Work'

# PERSONS
df_person = person.copy()
# add home RGC
df_person = util.get_is_rgc(df_person, 'hh_rgc')

# VMT
df_vmt = vmt.copy()
# add home RGC
df_vmt = util.get_is_rgc(df_vmt, 'hh_rgc')

# Select only walk and bike trips
df_vmt_bp = df_vmt[df_vmt['mode'].isin(['Walk','Bike'])].copy()
# Select only drivers (dorp = 1) and auto trips
df_vmt = df_vmt[df_vmt['mode'].isin(['SOV','HOV2','HOV3+']) & (df_vmt['dorp'] == 1)].copy()

# total population by equity geography
equity_geogs_population = df_person[equity_geogs].apply(lambda x: x * df_person['psexpfac']).sum().reset_index()
equity_geogs_population.columns = ['Equity Group', 'psexpfac']

df_vmt_bp2 = df_vmt_bp.copy()
df_vmt_bp2['mode'] = 'Walk and Bike'
# add walk and bike
df_vmt_bp2 = pd.concat([df_vmt_bp, df_vmt_bp2])

In [3]:
def walk_bike_per_person(geog, map=False):
    
    # miles by mode and geography
    df1 = df_vmt_bp2.groupby([geog, 'mode'], as_index=False)['travdist_wt'].sum().set_index(geog)

    if map:
        df1.index = df1.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

    # add total miles in region
    df1_region = df_vmt_bp2.groupby(['mode'])['travdist_wt'].sum().reset_index()
    df1_region[geog] = 'Region'
    df1_region = df1_region.set_index(geog)
    df1 = pd.concat([df1, df1_region])

    # population by geography
    df3 = df_person.groupby(geog, as_index=False)['psexpfac'].sum().set_index(geog)
    if map:
        df3.index = df3.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })
    df3.loc['Region',:] = df3.sum(axis=0)

    # calculate average miles per person
    df = df1.merge(df3, on=geog)
    df['Average Miles per Person'] = df['travdist_wt']/df['psexpfac']

    return df.pivot(columns='mode', values='Average Miles per Person')

:::{.panel-tabset}

### County and Region

In [4]:
pd.set_option('display.float_format', '{:,.2f}'.format)
walk_bike_per_person('hh_county')

mode       Bike  Walk  Walk and Bike
hh_county
King       0.23  0.66           0.89
Kitsap     0.16  0.54           0.70
Pierce     0.18  0.54           0.72
Region     0.21  0.59           0.80
Snohomish  0.18  0.51           0.69

### Regional Growth Center

In [5]:
walk_bike_per_person('is_rgc')

mode        Bike  Walk  Walk and Bike
is_rgc
In RGC      0.27  1.10           1.37
Not in RGC  0.20  0.53           0.73
Region      0.21  0.59           0.80

In [6]:
walk_bike_per_person('hh_rgc')

mode                             Bike  Walk  Walk and Bike
hh_rgc
Auburn                           0.34  0.71           1.05
Bellevue                         0.25  1.01           1.27
Bothell Canyon Park              0.22  0.58           0.80
Bremerton                        0.23  0.91           1.14
Burien                           0.31  0.62           0.93
Everett                          0.20  0.88           1.08
Federal Way                      0.30  0.74           1.04
Greater Downtown Kirkland        0.29  0.64           0.92
Issaquah                         0.26  0.72           0.98
Kent                             0.34  0.80           1.14
Kirkland Totem Lake              0.28  0.74           1.02
Lakewood                         0.28  0.83           1.11
Lynnwood                         0.32  0.86           1.18
Not in RGC                       0.20  0.53           0.73
Puyallup Downtown                0.32  0.73           1.05
Puyallup South Hill              0.19  0.72           0.91
Redmond Downtown                 0.39  0.89           1.29
Redmond-Overlake                 0.31  0.92           1.23
Region                           0.21  0.59           0.80
Renton                           0.33  0.80           1.13
SeaTac                           0.30  0.72           1.02
Seattle Downtown                 0.18  1.44           1.63
Seattle First Hill/Capitol Hill  0.23  1.49           1.73
Seattle Northgate                0.43  0.95           1.39
Seattle South Lake Union         0.22  1.37           1.59
Seattle University Community     0.40  1.10           1.50
Seattle Uptown                   0.29  1.36           1.65
Silverdale                       0.14  0.77           0.90
Tacoma Downtown                  0.25  1.12           1.37
Tacoma Mall                      0.28  0.93           1.21
Tukwila                          0.37  0.79           1.17
University Place                 0.25  0.73           0.98

### Regional Geography

In [7]:
walk_bike_per_person('hh_rg_proposed')

mode                               Bike  Walk  Walk and Bike
hh_rg_proposed
Cities and Towns                   0.15  0.45           0.60
Core Cities                        0.22  0.58           0.80
High Capacity Transit Communities  0.19  0.52           0.71
Metropolitan Cities                0.24  0.83           1.06
Region                             0.21  0.59           0.80
Rural Areas                        0.16  0.32           0.49
Urban Unincorporated Areas         0.17  0.45           0.62

### Equity Focus Areas

In [8]:
efa_col_dict = {
    "People of Color": "hh_efa_poc",
    "Income": "hh_efa_pov200",
    "LEP": "hh_efa_lep",
    "Disability": "hh_efa_dis",
    "Older Adults": "hh_efa_older",
    "Youth": "hh_efa_youth"
    }

In [9]:
df = pd.DataFrame()
for label, col in efa_col_dict.items():
    _df = walk_bike_per_person(col, map=True)
    _df = _df.drop('Region', axis=0)
    _df['Group'] = label
    df = pd.concat([df, _df])
df = df.reset_index()
df.rename(columns={'index': 'EFA Type'}, inplace=True)
df

mode,EFA Type,Bike,Walk,Walk and Bike,Group
0,Above Regional Average,0.22,0.65,0.87,People of Color
1,Below Regional Average,0.19,0.55,0.74,People of Color
2,Higher Share of Equity Population,0.23,0.65,0.88,People of Color
3,Above Regional Average,0.21,0.61,0.82,Income
4,Below Regional Average,0.20,0.56,0.76,Income
5,Higher Share of Equity Population,0.23,0.71,0.94,Income
6,Above Regional Average,0.22,0.61,0.82,LEP
7,Below Regional Average,0.19,0.59,0.78,LEP
8,Higher Share of Equity Population,0.23,0.61,0.84,LEP
9,Above Regional Average,0.20,0.59,0.79,Disability
10,Below Regional Average,0.21,0.58,0.78,Disability
11,Higher Share of Equity Population,0.21,0.68,0.88,Disability
12,Above Regional Average,0.19,0.56,0.75,Older Adults
13,Below Regional Average,0.22,0.63,0.84,Older Adults
14,Higher Share of Equity Population,0.20,0.56,0.76,Older Adults
15,Above Regional Average,0.19,0.50,0.69,Youth
16,Below Regional Average,0.22,0.69,0.91,Youth
17,Higher Share of Equity Population,0.18,0.46,0.64,Youth

:::

## Median Trip Distance by Mode and Home Location

:::{.panel-tabset}

### County

In [10]:
trip = pl.read_csv(util.output_path / 'daysim/_trip.tsv',separator='\t')
hh = pl.read_csv(util.output_path / 'daysim/_household.tsv',separator='\t')

list_cols = ['ParcelID','CountyName','GrowthCenterName','rg_proposed', 'People of Color', 'Income', 'LEP', 'Disability',
       'Older Adults', 'Youth']
parcel_geog = util.get_parcel_geog()[list_cols]

In [11]:
# trip table with home location
df_trip_hh = trip.join(hh, on="hhno", how="left").to_pandas()
df_trip_hh = df_trip_hh.merge(parcel_geog, how='left', left_on='hhparcel', right_on='ParcelID')
df_trip_hh['mode_label'] = df_trip_hh['mode'].map(
    {1: 'Walk',
     2: 'Bike',
     3: 'Drive Alone',
     4: 'Shared Ride',
     5: 'Shared Ride',
     6: 'Transit'}
     )

df_trip_hh = df_trip_hh[df_trip_hh['CountyName']!='Outside Region']
df_trip_hh = util.get_is_rgc(df_trip_hh, 'GrowthCenterName', 'is_rgc')

In [12]:
def get_median_time_distance(df, geog, value_col):

    df_geog = pd.pivot_table(df, index=geog, columns='mode_label', aggfunc='median', values=value_col)
    
    return df_geog


df = get_median_time_distance(df_trip_hh,'CountyName','travdist')
df_region =  get_median_time_distance(df_trip_hh,None,'travdist')
df.loc['Region'] = df_region.iloc[0]
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
CountyName
King        1.59         3.66         2.71     4.61  0.59
Kitsap      1.67         2.99         2.39    13.97  0.68
Pierce      1.74         3.73         2.80     4.59  0.71
Snohomish   1.76         3.66         2.63     7.65  0.75
Region      1.66         3.63         2.69     4.94  0.64

### Regional Geography

In [13]:
df = get_median_time_distance(df_trip_hh,'rg_proposed','travdist')
df

mode_label,Bike,Drive Alone,Shared Ride,Transit,Walk
rg_proposed,,,,,
Cities and Towns,1.62,4.49,2.79,10.35,0.75
Core Cities,1.80,3.43,2.54,7.94,0.73
High Capacity Transit Communities,1.90,3.61,2.68,9.00,0.83
Metropolitan Cities,1.35,2.59,1.96,3.34,0.53
Rural Areas,3.04,6.46,5.45,13.55,0.94
Urban Unincorporated Areas,2.06,4.27,3.21,10.32,1.01

### Regional Growth Center

In [14]:
df = get_median_time_distance(df_trip_hh,'is_rgc','travdist')
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
is_rgc
In RGC      1.00         1.81         1.32     1.92  0.42
Not in RGC  1.89         3.74         2.78     6.02  0.79

In [15]:
df = get_median_time_distance(df_trip_hh,'GrowthCenterName','travdist')
df

mode_label                       Bike  Drive Alone  Shared Ride  Transit  Walk
GrowthCenterName
Auburn                           1.55         2.11         1.37    10.46  0.35
Bellevue                         0.68         1.09         0.87     5.06  0.32
Bothell Canyon Park              1.65         3.52         2.63     8.93  0.61
Bremerton                        1.06         1.18         0.85    23.68  0.34
Burien                           1.70         4.18         2.17     8.23  0.38
Everett                          0.80         0.99         0.74     1.26  0.35
Federal Way                      1.51         2.58         1.78     7.81  0.44
Greater Downtown Kirkland        1.99         3.02         1.98     9.03  0.47
Issaquah                         1.12         4.71         1.78     9.69  0.40
Kent                             1.38         1.94         0.94     8.89  0.33
Kirkland Totem Lake              1.34         3.10         1.79     7.26  0.66
Lakewood                         1.34         1.77         1.18     7.42  0.47
Lynnwood                         1.63         2.28         1.73     8.64  0.51
Not in RGC                       1.89         3.74         2.78     6.02  0.79
Puyallup Downtown                1.29         2.37         1.60    10.95  0.43
Puyallup South Hill              1.62         1.99         1.55    11.32  0.63
Redmond Downtown                 1.32         2.65         1.40     6.85  0.45
Redmond-Overlake                 1.02         1.75         1.30     4.02  0.50
Renton                           1.52         3.21         1.88     7.59  0.40
SeaTac                           1.70         3.37         2.68     5.99  0.65
Seattle Downtown                 0.76         0.91         0.87     1.00  0.37
Seattle First Hill/Capitol Hill  1.00         1.14         1.01     1.23  0.49
Seattle Northgate                2.35         3.52         2.16     6.69  0.60
Seattle South Lake Union         0.83         1.03         0.93     1.17  0.39
Seattle University Community     1.07         2.65         1.77     4.03  0.53
Seattle Uptown                   1.03         1.29         1.10     1.51  0.48
Silverdale                       0.89         0.89         0.77    36.23  0.46
Tacoma Downtown                  0.91         1.34         1.04     1.58  0.42
Tacoma Mall                      1.41         1.94         1.52     4.07  0.58
Tukwila                          2.11         2.65         2.11     8.78  0.66
University Place                 1.39         2.56         1.68     4.51  0.61

### Equity Focus Areas

In [16]:
df = pd.DataFrame()
for col in efa_col_dict.keys():
    _df = get_median_time_distance(df_trip_hh,col,'travdist').reset_index()
    _df['Group'] = col
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

mode_label                                         Bike  Drive Alone  \
Group           EFA Type
People of Color Above Regional Average             1.56         3.40
                Below Regional Average             1.75         3.83
                Higher Share of Equity Population  1.62         3.47
Income          Above Regional Average             1.63         3.32
                Below Regional Average             1.74         3.96
                Higher Share of Equity Population  1.47         2.85
LEP             Above Regional Average             1.68         3.73
                Below Regional Average             1.63         3.68
                Higher Share of Equity Population  1.74         3.34
Disability      Above Regional Average             1.65         3.52
                Below Regional Average             1.73         3.83
                Higher Share of Equity Population  1.46         3.06
Older Adults    Above Regional Average             1.73         3.83
                Below Regional Average             1.60         3.46
                Higher Share of Equity Population  1.77         3.86
Youth           Above Regional Average             1.92         3.96
                Below Regional Average             1.50         3.18
                Higher Share of Equity Population  1.92         4.51

mode_label                                         Shared Ride  Transit  Walk
Group           EFA Type
People of Color Above Regional Average                    2.51     4.31  0.60
                Below Regional Average                    2.85     5.30  0.68
                Higher Share of Equity Population         2.60     5.17  0.61
Income          Above Regional Average                    2.46     4.91  0.64
                Below Regional Average                    2.95     5.36  0.66
                Higher Share of Equity Population         2.19     4.23  0.58
LEP             Above Regional Average                    2.76     5.87  0.62
                Below Regional Average                    2.74     4.43  0.63
                Higher Share of Equity Population         2.48     6.12  0.70
Disability      Above Regional Average                    2.62     5.42  0.66
                Below Regional Average                    2.85     5.00  0.67
                Higher Share of Equity Population         2.27     3.49  0.55
Older Adults    Above Regional Average                    2.85     5.63  0.65
                Below Regional Average                    2.55     4.40  0.63
                Higher Share of Equity Population         2.97     6.76  0.63
Youth           Above Regional Average                    2.93     7.20  0.80
                Below Regional Average                    2.38     4.23  0.57
                Higher Share of Equity Population         3.15     7.78  0.88

:::

## Median Time Spent Walking/Biking
Time in minutes

:::{.panel-tabset}

### County

In [17]:

df = get_median_time_distance(df_trip_hh,'CountyName','travtime')
df_region =  get_median_time_distance(df_trip_hh,None,'travtime')
df.loc['Region'] = df_region.iloc[0]
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
CountyName
King       10.61        12.47        10.42    25.59 11.77
Kitsap     11.16        10.50         9.40    74.32 13.51
Pierce     11.60        12.31        10.59    33.39 14.17
Snohomish  11.72        11.47         9.42    33.68 15.05
Region     11.05        12.10        10.19    27.52 12.73

### Regional Geography

In [18]:
df = get_median_time_distance(df_trip_hh,'rg_proposed','travtime')
df

mode_label,Bike,Drive Alone,Shared Ride,Transit,Walk
rg_proposed,,,,,
Cities and Towns,10.80,12.50,9.63,48.29,15.08
Core Cities,11.99,11.22,9.48,38.65,14.54
High Capacity Transit Communities,12.65,11.52,9.66,37.25,16.55
Metropolitan Cities,8.99,11.60,9.94,20.15,10.57
Rural Areas,20.25,16.06,14.60,61.68,18.72
Urban Unincorporated Areas,13.73,12.41,10.59,48.13,20.20

### Regional Growth Center

In [19]:
df = get_median_time_distance(df_trip_hh,'is_rgc','travtime')
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
is_rgc
In RGC      6.64        10.58         9.17    15.21  8.37
Not in RGC 12.59        12.24        10.26    31.42 15.74

In [20]:
df = get_median_time_distance(df_trip_hh,'GrowthCenterName','travtime')
df

mode_label                       Bike  Drive Alone  Shared Ride  Transit  Walk
GrowthCenterName
Auburn                          10.36         9.48         8.06    44.80  6.96
Bellevue                         4.54         7.83         7.03    25.58  6.41
Bothell Canyon Park             11.02        11.57         9.68    46.67 12.12
Bremerton                        7.04         9.52         8.57    61.35  6.81
Burien                          11.33        11.47         8.12    40.14  7.51
Everett                          5.35         7.16         6.40    14.00  7.04
Federal Way                     10.09         9.70         7.62    28.40  8.79
Greater Downtown Kirkland       13.24        10.23         8.41    34.50  9.44
Issaquah                         7.44        12.65         6.87    59.08  7.99
Kent                             9.18         7.65         5.89    40.76  6.60
Kirkland Totem Lake              8.94        10.01         7.77    32.70 13.23
Lakewood                         8.90         9.47         8.25    43.19  9.31
Lynnwood                        10.87         9.82         8.61    31.41 10.21
Not in RGC                      12.59        12.24        10.26    31.42 15.74
Puyallup Downtown                8.57         9.63         8.38    59.47  8.53
Puyallup South Hill             10.81         8.41         7.25    60.10 12.59
Redmond Downtown                 8.81         8.59         6.38    31.04  8.92
Redmond-Overlake                 6.81         7.65         6.31    21.65 10.09
Renton                          10.10        11.75         9.06    37.16  7.98
SeaTac                          11.33        11.68        10.48    35.68 13.10
Seattle Downtown                 5.04        11.02        10.73     8.25  7.31
Seattle First Hill/Capitol Hill  6.66        10.87        10.22    11.22  9.79
Seattle Northgate               15.70        12.91         9.80    23.64 11.96
Seattle South Lake Union         5.51        11.22        10.76    10.80  7.83
Seattle University Community     7.10        12.92        10.83    16.47 10.59
Seattle Uptown                   6.85        11.53        10.89    12.78  9.67
Silverdale                       5.91         5.00         4.58    88.64  9.25
Tacoma Downtown                  6.05        11.06        10.28    15.03  8.30
Tacoma Mall                      9.43         9.93         8.96    30.52 11.59
Tukwila                         14.04        10.25         8.85    38.49 13.18
University Place                 9.25        10.71         8.54    29.94 12.16

### Equity Focus Areas

In [21]:
df = pd.DataFrame()
for col in efa_col_dict.keys():
    _df = get_median_time_distance(df_trip_hh,col,'travtime').reset_index()
    _df['Group'] = col
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

mode_label                                         Bike  Drive Alone  \
Group           EFA Type
People of Color Above Regional Average            10.38        11.61
                Below Regional Average            11.66        12.53
                Higher Share of Equity Population 10.77        11.70
Income          Above Regional Average            10.85        11.53
                Below Regional Average            11.58        12.64
                Higher Share of Equity Population  9.83        10.94
LEP             Above Regional Average            11.21        11.95
                Below Regional Average            10.84        12.39
                Higher Share of Equity Population 11.60        11.34
Disability      Above Regional Average            10.98        11.87
                Below Regional Average            11.56        12.46
                Higher Share of Equity Population  9.72        11.25
Older Adults    Above Regional Average            11.51        12.43
                Below Regional Average            10.70        11.82
                Higher Share of Equity Population 11.80        12.38
Youth           Above Regional Average            12.81        12.30
                Below Regional Average             9.98        11.77
                Higher Share of Equity Population 12.81        12.90

mode_label                                         Shared Ride  Transit  Walk
Group           EFA Type
People of Color Above Regional Average                    9.80    25.36 11.96
                Below Regional Average                   10.55    27.80 13.66
                Higher Share of Equity Population         9.91    30.05 12.14
Income          Above Regional Average                    9.77    27.07 12.73
                Below Regional Average                   10.59    28.80 13.20
                Higher Share of Equity Population         9.49    23.88 11.70
LEP             Above Regional Average                   10.04    29.43 12.37
                Below Regional Average                   10.48    24.88 12.53
                Higher Share of Equity Population         9.54    32.34 13.93
Disability      Above Regional Average                   10.02    28.66 13.13
                Below Regional Average                   10.43    27.68 13.36
                Higher Share of Equity Population         9.71    23.94 10.99
Older Adults    Above Regional Average                   10.55    30.71 12.98
                Below Regional Average                    9.87    25.06 12.61
                Higher Share of Equity Population        10.76    31.06 12.64
Youth           Above Regional Average                   10.28    36.36 16.00
                Below Regional Average                   10.02    23.79 11.32
                Higher Share of Equity Population        10.52    40.36 17.56

:::

## % Population Walking or Biking for Transportation
Does not include people making exercise trips

In [22]:
bike_walk_trips = trip.filter(pl.col("mode").is_in([1, 2]))

# Get unique persons with at least one bike/walk trip
bike_walk_persons = bike_walk_trips.select(["hhno", "pno"]).unique()
bike_walk_persons = bike_walk_persons.with_columns(bike_walk=pl.lit(1))

# Join back to all persons, mark bike_walk as False if not present
person = pl.read_csv(util.output_path / 'daysim/_person.tsv',separator='\t')
person_with_bike_walk = person.join(bike_walk_persons, on=["hhno", "pno"], how="left")
person_with_bike_walk = person_with_bike_walk.join(hh, on='hhno', how='left')

person_with_bike_walk = person_with_bike_walk.to_pandas()
person_with_bike_walk = person_with_bike_walk.merge(parcel_geog, how='left', left_on='hhparcel', right_on='ParcelID')

person_with_bike_walk['bike_walk'] = person_with_bike_walk['bike_walk'].fillna(0)


person_with_bike_walk = person_with_bike_walk[person_with_bike_walk['CountyName']!='Outside Region']
person_with_bike_walk = util.get_is_rgc(person_with_bike_walk, 'GrowthCenterName', 'is_rgc')

:::{.panel-tabset}
### County

In [23]:
def get_pop_bike_walk(df, geog):
    df = pd.pivot_table(df, index=geog, columns='bike_walk', aggfunc='sum', values='psexpfac')
    df['% Biking or Walking'] = df[1]/(df[0]+df[1])
    return df[['% Biking or Walking']]

In [24]:
pd.set_option('display.float_format', '{:.1%}'.format)
df = get_pop_bike_walk(person_with_bike_walk, 'CountyName')
df_region =  get_pop_bike_walk(person_with_bike_walk, None)
df.loc['Region'] = df_region.iloc[0]
df

bike_walk   % Biking or Walking
CountyName
King                      33.1%
Kitsap                    26.6%
Pierce                    25.0%
Snohomish                 24.5%
Region                    29.2%

### Regional Geography

In [25]:
df = get_pop_bike_walk(person_with_bike_walk, 'rg_proposed')
df

bike_walk                          % Biking or Walking
rg_proposed
Cities and Towns                                 22.8%
Core Cities                                      28.0%
High Capacity Transit Communities                24.0%
Metropolitan Cities                              43.2%
Rural Areas                                      13.0%
Urban Unincorporated Areas                       18.7%

### Regional Growth Center

In [26]:
df = get_pop_bike_walk(person_with_bike_walk, 'is_rgc')
df

bike_walk   % Biking or Walking
is_rgc
In RGC                    62.3%
Not in RGC                25.2%

In [27]:
df = get_pop_bike_walk(person_with_bike_walk, 'GrowthCenterName')
df

bike_walk                        % Biking or Walking
GrowthCenterName
Auburn                                         48.8%
Bellevue                                       70.9%
Bothell Canyon Park                            29.4%
Bremerton                                      61.5%
Burien                                         42.4%
Everett                                        62.1%
Federal Way                                    44.8%
Greater Downtown Kirkland                      37.9%
Issaquah                                       45.2%
Kent                                           57.6%
Kirkland Totem Lake                            39.5%
Lakewood                                       47.6%
Lynnwood                                       45.4%
Not in RGC                                     25.2%
Puyallup Downtown                              43.8%
Puyallup South Hill                            34.9%
Redmond Downtown                               53.6%
Redmond-Overlake                               53.9%
Renton                                         48.3%
SeaTac                                         35.8%
Seattle Downtown                               81.8%
Seattle First Hill/Capitol Hill                75.2%
Seattle Northgate                              47.4%
Seattle South Lake Union                       77.0%
Seattle University Community                   58.8%
Seattle Uptown                                 70.5%
Silverdale                                     47.8%
Tacoma Downtown                                65.1%
Tacoma Mall                                    47.3%
Tukwila                                        40.8%
University Place                               38.8%

### Equity Focus Areas

In [28]:
df = pd.DataFrame()
for col in efa_col_dict.keys():
    _df = get_pop_bike_walk(person_with_bike_walk,col).reset_index()
    _df['Group'] = col
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

bike_walk                                          % Biking or Walking
Group           EFA Type
People of Color Above Regional Average                           32.2%
                Below Regional Average                           26.7%
                Higher Share of Equity Population                31.9%
Income          Above Regional Average                           30.2%
                Below Regional Average                           27.1%
                Higher Share of Equity Population                35.9%
LEP             Above Regional Average                           29.4%
                Below Regional Average                           29.0%
                Higher Share of Equity Population                29.9%
Disability      Above Regional Average                           28.7%
                Below Regional Average                           28.0%
                Higher Share of Equity Population                34.4%
Older Adults    Above Regional Average                           27.0%
                Below Regional Average                           31.1%
                Higher Share of Equity Population                27.3%
Youth           Above Regional Average                           23.5%
                Below Regional Average                           35.1%
                Higher Share of Equity Population                21.1%

:::

## Bike and Walk Tours by Purpose
Tours where most or all trips are by the mode.

In [29]:
df = pd.read_csv(util.output_path / 'agg/dash/tour_total.csv')

df['Tour Mode'] = df['tmodetp'].map({'SOV': 'Drove Alone',
                                     'HOV2': 'Shared Ride',
                                     'HOV3+': 'Shared Ride',
                                     'Transit': 'Transit',
                                     'Walk': 'Walk',
                                     'Bike': 'Bike'
                                     })

df = pd.pivot_table(df, index='pdpurp', columns='Tour Mode', values='toexpfac', aggfunc='sum')
df = df/df.sum()
df[['Transit', 'Walk', 'Bike','Drove Alone', 'Shared Ride', ]]

Tour Mode          Transit  Walk  Bike  Drove Alone  Shared Ride
pdpurp
Escort                0.0%  7.7%  3.2%         1.0%        22.8%
Meal                  8.2% 10.6%  1.7%         4.9%         7.8%
Personal Business    11.8%  5.5%  3.9%         8.2%         5.8%
School               18.1%  4.0% 16.0%         3.8%        11.1%
Shop                 16.7% 12.3%  7.6%        15.0%        11.0%
Social               18.6% 47.4% 38.1%        21.4%        23.2%
Work                 26.5% 12.5% 29.4%        45.7%        18.3%

## Average Jobs Accessible within 1 Mile Walk and 3 Mile Bike
Note that this is not using the bike network, but is instead using the all-streets network.

Average accessible jobs are weighted averages based on parcel household population.

In [30]:
# total jobs
parcel_emp = util.get_parcels_urbansim_data()[['parcelid','emptot_p']]
tot_jobs = parcel_emp['emptot_p'].sum()

In [31]:
walk_bike_jobs_access = pd.read_csv(util.output_path / 'access/walk_bike_jobs_access.csv', 
                                  usecols=['geography_value', 'jobs_1_mile_walk', 'jobs_3_mile_bike', 'geography_group']).\
                                  rename(columns={'geography_value': 'geography'})

df_access = walk_bike_jobs_access.copy()
df_access = df_access[df_access['geography'] != 'Outside Region']
# rename region
df_access.loc[df_access['geography_group'] == 'region', 'geography'] = 'Region'
# rename rgc
df_access.loc[df_access['geography_group'] == 'rgc_binary', 'geography'] = ['Not in RGC', 'In RGC']
# rename efa 
# jobs access in equity geographies
equity_geogs = util.summary_config['equity_geogs']
df_access.loc[df_access['geography_group'].isin(equity_geogs), 'geography'] = df_access.loc[df_access['geography_group'].isin(equity_geogs), 'geography'].\
    map({"0.0": 'Below Regional Average', 
         "1.0": 'Above Regional Average', 
         "2.0": 'Higher Share of Equity Population'}
         )

:::{.panel-tabset}

### Region and County

In [32]:
def bp_job_access_geog(access_table,geog):
    df = access_table.loc[access_table['geography_group'].isin(geog)].\
        rename(columns={'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                        'jobs_3_mile_bike': 'Jobs within 3-mile Bike'}).\
        drop(columns=['geography_group']).\
        set_index('geography')

    df['% Total Jobs (1-mile Walk)'] = df['Jobs within 1-mile Walk'].apply(lambda x: x / tot_jobs)
    df['% Total Jobs (3-mile Bike)'] = df['Jobs within 3-mile Bike'].apply(lambda x: x / tot_jobs)

    

    return df

format_dict = {
        'Jobs within 1-mile Walk': "{:.0f}",
        'Jobs within 3-mile Bike': "{:.0f}", 
        '% Total Jobs (1-mile Walk)': "{:.1%}", 
        '% Total Jobs (3-mile Bike)': "{:.1%}"
    }

In [33]:
df = bp_job_access_geog(df_access,['region','CountyName'])
df.style.format(format_dict)

### Regional Growth Center

In [34]:
df = bp_job_access_geog(df_access,['rgc_binary'])
df.style.format(format_dict)

In [35]:
df = bp_job_access_geog(df_access,['GrowthCenterName'])
df.style.format(format_dict)

### Regional Geography

In [36]:
df = bp_job_access_geog(df_access,['rg_proposed'])
df.style.format(format_dict)

### Equity Focus Areas

In [37]:
efa_geog_dict = {
    "People of Color": "equity_focus_areas_2023__efa_poc",
    "Income": "equity_focus_areas_2023__efa_pov200",
    "LEP": "equity_focus_areas_2023__efa_lep",
    "Disability": "equity_focus_areas_2023__efa_dis",
    "Older Adults": "equity_focus_areas_2023__efa_older",
    "Youth": "equity_focus_areas_2023__efa_youth"
    }

df = pd.DataFrame()
for label, col in efa_geog_dict.items():
    _df = bp_job_access_geog(df_access,[col])
    _df['Group'] = label
    df = pd.concat([df, _df])
df = df.reset_index()
df.rename(columns={'geography': 'EFA Type'}, inplace=True)
df.set_index(['Group','EFA Type']).style.format(format_dict)

:::