In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": True, "run_validation": True, "run_network_validation": True, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "daysim-validation-notebook": ["all_tour_mode", "all_trip_mode", "auto_ownership", "day_pattern", "escort_tour_mode", "escort_trip_mode", "households", "intermediate_stop_generation", "other_home_based_tour_mode", "other_home_based_trip_mode", "persons", "school_location", "school_tour_mode", "school_trip_mode", "telecommute", "time_choice", "tours", "tour_destination", "transit_pass_ownership", "trips", "trip_destination", "workbased_subtour_generation", "workbased_subtour_mode", "work_location", "work_tour_mode", "work_trip_mode"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "../../../../inputs/base_year/survey"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to6": 5, "6to7": 6, "7to8": 7, "8to9": 8, "9to10": 9, "10to14": 10, "14to15": 14, "15to16": 15, "16to17": 16, "17to18": 17, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "base_year_2023_final", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/rtp_2026_2050", "abm_model": "daysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_daysim": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": True, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}

---
title: "System Performance"
date: today
---

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
import polars as pl
import util

pd.set_option('display.float_format', '{:,.0f}'.format)

In [3]:
# trip data
hh = pd.read_csv(util.output_path / 'agg/dash/hh_geog.csv')
# person data
person = pd.read_csv(util.output_path / 'agg/dash/pptyp_county.csv')
# worker data
employment = pd.read_csv(util.output_path / 'agg/dash/person_worker_type.csv')
# network data
df_network = util.process_network_summary()
# job data
df_lu = util.get_parcels_urbansim_data(inc_geog=True)

In [4]:
county_order = ['King','Kitsap','Pierce','Snohomish','Outside Region','Total']

person['person_county'] = pd.Categorical(person['person_county'], ordered=True,
                   categories=county_order)
hh['hh_county'] = pd.Categorical(hh['hh_county'], ordered=True,
                   categories=county_order)
employment['person_work_county'] = pd.Categorical(employment['person_work_county'], ordered=True,
                   categories=county_order)

df_network['county'] = pd.Categorical(df_network['county'], ordered=True,
                   categories=county_order)

In [5]:
#| label: total_vmt_vht_delay_by_county

df_vmt = df_network.reset_index().groupby('county',observed=True)['VMT'].sum()
df_vht = df_network.reset_index().groupby('county',observed=True)['VHT'].sum()
df_delay = df_network.reset_index().groupby('county',observed=True)['total_delay'].sum()

df = pd.concat([df_vmt,df_vht,df_delay], axis=1)
df = df[df.index!='Outside Region']
df.rename(columns={'total_delay': 'Total Delay Hours'}, inplace=True)

df.loc['Total',] = df.sum()
total_vmt = df.loc['Total','VMT']

# df.style.format('{:,.0f}')

## Households, Population and Vehicles

In [6]:
auto_ownership = pd.read_csv(util.output_path / 'agg/dash/auto_ownership.csv')
df_vehicle = auto_ownership.groupby('hh_county', observed=True).apply(lambda x: (x['hhvehs'] * x['hhexpfac']).sum(),include_groups=False)
df_vehicle.name = 'Vehicles'

In [7]:
# Total Population
df_person = person[['person_county','psexpfac']].groupby('person_county', observed=True)['psexpfac'].sum()
df_person.name = 'Persons'
df_hh = hh[['hh_county','hhexpfac']].groupby('hh_county', observed=True)['hhexpfac'].sum()
df_hh.name = 'Households'

df = pd.concat([df_person,df_hh,df_vehicle],axis=1)
df = df[df.index!='Outside Region']

df.loc['Total',] = df.sum()

df

            Persons  Households  Vehicles
King      2,303,851     957,460 1,628,963
Kitsap      275,120     108,901   223,716
Pierce      925,555     350,141   687,974
Snohomish   851,485     319,624   644,792
Total     4,356,011   1,736,126 3,185,445

## Workers and Jobs
By Workplace Location

Workers are Daysim outputs and Jobs are Parcel Inputs

In [8]:
# Jobs
df_jobs = df_lu[['emptot_p','CountyName']].groupby('CountyName').sum()[['emptot_p']]
df_jobs = df_jobs.reset_index()
df_jobs.rename(columns={'emptot_p': 'Jobs',
                   'CountyName':'County'}, inplace=True)
df_jobs.set_index('County')
df_jobs['Jobs'] = df_jobs['Jobs'].astype('float')

# workers
df = employment.groupby('person_work_county',observed=True)['psexpfac'].sum()

df = df.reset_index()
df.rename(columns={'psexpfac': 'Workers',
                   'person_work_county':'County'}, inplace=True)
df.set_index('County')
df['Workers'] = df['Workers'].astype('float')
df = df.merge(df_jobs, on='County')

df.loc['Total',:] = df.sum(axis=0, numeric_only=True)

df.loc['Total','County'] = 'Region'
df.reset_index(drop=True)

      County   Workers      Jobs
0       King 1,443,578 1,442,506
1     Kitsap   102,107    98,821
2     Pierce   353,537   323,128
3  Snohomish   327,710   290,359
4     Region 2,226,932 2,154,814

## VMT by Type

In [9]:
vmt_df = pd.DataFrame()

# Daysim Resident Demand
df = pd.read_csv(util.output_path / 'agg/dash/person_vmt.csv')
df = df[df['mode'].isin(['SOV','HOV2','HOV3+']) & df['dorp']==1]
vmt_df.loc['Resident','VMT'] = df['travdist_wt'].sum()

# Trucks
df_network['medium_truck_vmt'] = df_network['@medium_truck']*df_network['length']
df_network['heavy_truck_vmt'] = df_network['@heavy_truck']*df_network['length']

vmt_df.loc['Medium Truck','VMT'] = df_network['medium_truck_vmt'].sum()
vmt_df.loc['Heavy Truck','VMT'] = df_network['heavy_truck_vmt'].sum()

# Externals
external_vmt = total_vmt - vmt_df['VMT'].sum()
vmt_df.loc['External and Other'] = external_vmt

vmt_df.loc['Total'] = total_vmt
vmt_df

                          VMT
Resident           62,697,932
Medium Truck        4,804,156
Heavy Truck         5,207,885
External and Other  9,428,096
Total              82,138,070

## Vehicle Trips (Resident + External)

In [10]:
# Trips
df = pd.read_csv(util.output_path / 'trips_by_class.csv')
df.columns = ['class','trips','tod']
df['mode'] = df['class'].map({'sov_inc1': 'Drive Alone',
                 'sov_inc2': 'Drive Alone',
                 'sov_inc3': 'Drive Alone',
                 'hov2_inc1': 'Shared Ride',
                 'hov2_inc2': 'Shared Ride',
                 'hov2_inc3': 'Shared Ride',
                 'hov3_inc1': 'Shared Ride',
                 'hov3_inc2': 'Shared Ride',
                 'hov3_inc3': 'Shared Ride'})
df = df.groupby('mode').sum()[['trips']].reset_index()
df

          mode     trips
0  Drive Alone 7,672,357
1  Shared Ride 3,171,375

## Emissions
Daily Tons for light, medium, and heavy vehicles; bus vehicles are excluded.

In [11]:
df = pd.read_csv(util.output_path / 'emissions/emissions_summary.csv')

df = df[df['veh_type'].isin(['light','medium','heavy'])]
df = df.groupby('pollutant_name').sum()
df.rename(columns={'start_tons': 'Start', 'intrazonal_tons': 'Intrazonal', 'interzonal_tons': 'Interzonal',
                  'total_daily_tons': 'Total Daily'},
                  inplace=True)
df = df.loc[df.index.isin(['CO','NOx','PM25 Total','PM10 Total','CO2 Equivalent']),
            ['Start', 'Intrazonal', 'Interzonal', 'Total Daily']]

df

                Start  Intrazonal  Interzonal  Total Daily
pollutant_name
CO                122           2         238          363
CO2 Equivalent  2,273         250      37,112       39,635
NOx                 8           0          37           45
PM10 Total          0           0           5            5
PM25 Total          0           0           1            2

## Lane Miles

In [12]:
facility_type_dict = {
    1: 'Interstate',
    2: 'Other Freeway',
    3: 'Expressway',
    4: 'Ramp',
    5: 'Principal Arterial',
    6: 'Minor Arterial',
    7: 'Major Collector',
    8: 'Minor Collector',
    9: 'Local',
    10: 'Busway',
    11: 'Non-Motor',
    12: 'Light Rail',
    13: 'Commuter Rail',
    15: 'Ferry',
    16: 'Passenger-Only Ferry',
    17: 'Centroid Connector',
    18: 'Facility Connector',
    19: 'HOV Only Freeway',
    20: 'HOV Only Ramp',
    98: 'Weave Links'
}

ul3_dict = {
    0: 'Rail/Walk/Ferry',
    1: 'Freeway',
    2: 'Expressway',
    3: 'Urban Arterial',
    4: 'One-way Arterial',
    5: 'Centroid Connector',
    6: 'Rural Arterial'
}

county_dict = {
    33: 'King',
    35: 'Kitsap',
    53: 'Pierce',
    61: 'Snohomish'
}

In [13]:
# Select mid-day network
gdf = df_network.loc[df_network['tod'] == '10to14'].copy()
gdf['Lane Miles'] = gdf['length'] * gdf['num_lanes']

gdf['Facility Type'] = pd.Categorical(gdf['@facilitytype'].map(facility_type_dict), 
                                      ordered=True,
                                      categories=facility_type_dict.values())

df = gdf.groupby(['Facility Type'], observed=True)['Lane Miles'].sum().reset_index().set_index('Facility Type')

# df = df.drop(['@facilitytype','Facility Type'], axis=1)
df.loc['Total','Lane Miles'] = df['Lane Miles'].sum()
df

                    Lane Miles
Facility Type
Interstate               1,468
Other Freeway              767
Expressway                 229
Ramp                       537
Principal Arterial       3,101
Minor Arterial           4,064
Major Collector          2,925
Minor Collector            219
Local                      300
Centroid Connector       9,820
Facility Connector          19
HOV Only Freeway             3
HOV Only Ramp               20
Total                   23,471

In [14]:
gdf['Facility Group'] = pd.Categorical(gdf['data3'].map(ul3_dict), 
                                      ordered=True,
                                      categories=ul3_dict.values())

df = gdf.groupby(['Facility Group'], observed=True)['Lane Miles'].sum().reset_index().set_index('Facility Group')

df.loc['Total','Lane Miles'] = df['Lane Miles'].sum()
df

                    Lane Miles
Facility Group
Freeway                  2,236
Expressway                 677
Urban Arterial           6,874
One-way Arterial           453
Centroid Connector       9,839
Rural Arterial           3,340
Total                   23,417

In [15]:
# Load link attributes and join
gdf['county'] = gdf['county'].replace(np.nan,'Outside Region')
df = gdf.groupby(['county'], observed=True)['Lane Miles'].sum().reset_index().set_index('county')
df = df[df.index!="Outside Region"]

df.loc['Total','Lane Miles'] = df['Lane Miles'].sum()
df

           Lane Miles
county
King           10,802
Kitsap          2,022
Pierce          5,820
Snohomish       4,770
Total          23,413

# Person Metrics

In [16]:
# Daysim data

trip = pl.read_csv(util.output_path / 'daysim/_trip.tsv',separator='\t')
person = pl.read_csv(util.output_path / 'daysim/_person.tsv',separator='\t')
hh = pl.read_csv(util.output_path / 'daysim/_household.tsv', separator='\t')

### Average Daily Miles Driven per Person

In [17]:
if 'sov_ff_time' in trip.columns:
    drive_modes = [3, 4, 5]
    vehicle_trips = trip[['mode', 'dorp', 'travtime', 'sov_ff_time', 'travdist']].filter(pl.col("mode").is_in(drive_modes)).filter(pl.col("dorp") == 1)
    avg_vmt = vehicle_trips['travdist'].sum()/ person['psexpfac'].sum()
    print(f'Average Daily VMT per person, not including externals or trucks: {avg_vmt:.1f}')

Average Daily VMT per person, not including externals or trucks: 14.4

### Hours of Congestion per Person per Year
For average Puget Sound resident:

In [18]:
if 'sov_ff_time' in trip.columns:
    drive_trips = trip[['mode', 'dorp', 'travtime', 'sov_ff_time', 'travdist']].filter(pl.col("mode").is_in(drive_modes))
    drive_trips = drive_trips.with_columns(
        delay=pl.col('travtime')-(pl.col('sov_ff_time')/100.0))
    minutes_to_hour = 60
    drive_mode_delay = util.summary_config['weekday_to_annual']*(drive_trips['delay'].sum()/person['psexpfac'].sum())/minutes_to_hour
    print(f'Annual hours of delay for residents, not including externals or trucks is: {drive_mode_delay:.1f}')

Annual hours of delay for residents, not including externals or trucks is: 15.9

### Annual Hours of Delay by Average Truck
Average annual delay (hours) per truck trip in and through the region:

In [19]:
# Total truck trips

In [20]:
# Load truck trips
df = pd.read_csv(util.output_path / 'trucks/trucks_summary.csv',index_col=0)

# Truck delay
net_sum = pd.read_csv(util.output_path / 'network/delay_user_class.csv')

# Annual delay hours
daily_delay = net_sum[['@mveh','@hveh']].sum().sum()


# total truck trips
trips = df['prod'].sum()

# average annual delay hours per truck
x = (daily_delay*util.summary_config["weekday_to_annual"])/trips
print('{:0,.1f}'.format(x))

18.5

*Medium trucks only:*

In [21]:
x = (net_sum['@mveh'].sum()*util.summary_config["weekday_to_annual"])/df.loc['mt','prod']
print('{:0,.1f}'.format(x))

14.1

*Heavy trucks only:*

In [22]:
x = (net_sum['@hveh'].sum()*util.summary_config["weekday_to_annual"])/df.loc['ht','prod']
print ('{:0,.1f}'.format(x))

32.2

## % Population Walking or Biking for Transportation

In [23]:
trip_person = trip.join(person, on=["hhno", "pno"], how="left")
bike_walk_trips = trip_person.filter(pl.col("mode").is_in([1, 2]))

# Get unique persons with at least one bike/walk trip
bike_walk_persons = bike_walk_trips.select(["hhno", "pno"]).unique()
bike_walk_persons = bike_walk_persons.with_columns(bike_walk=pl.lit(True))

# Join back to all persons, mark bike_walk as False if not present
person_with_bike_walk = person.join(bike_walk_persons, on=["hhno", "pno"], how="left")
person_with_bike_walk = person_with_bike_walk.with_columns(
    pl.col("bike_walk").fill_null(False)
)

# Calculate share
share = (
    person_with_bike_walk.group_by("bike_walk")
    .agg(pl.col("psexpfac").sum())
    .with_columns(
        (pl.col("psexpfac") / pl.col("psexpfac").sum()).alias("share")
    )
)
print("Percent of population with at least one non-exercise walk or bike trip: {:.1%}".format(share.filter(pl.col("bike_walk") == True)["share"][0]))

Percent of population with at least one non-exercise walk or bike trip: 25.6%

## Household and Jobs within 1/4 mile transit

In [24]:
# Network data
df = pd.read_csv(util.output_path / 'transit/transit_access.csv',index_col=0)

**Households**

In [25]:
x = df.loc['hh_p','quarter_mile_transit']
print('{:,.0f}'.format(x) + (" households within 1/4 mile of transit"))
x = df.loc['hh_p','quarter_mile_transit']/df.loc['hh_p','total']
print('{:,.1%}'.format(x) + (" of total households"))

828,824 households within 1/4 mile of transit
47.7% of total households

**Jobs**

In [26]:
x = df.loc['emptot_p','quarter_mile_transit']
print('{:,.0f}'.format(x) + (" jobs within 1/4 mile of transit"))
x = df.loc['hh_p','quarter_mile_transit']/df.loc['emptot_p','total']
print('{:,.1%}'.format(x) + (" of total jobs"))

1,556,015 jobs within 1/4 mile of transit
38.5% of total jobs