In [1]:
# Parameters
summary_config = {"run_run_comparison": False, "run_RTP_summary": True, "run_validation": True, "run_network_validation": True, "summary_list": {"RTP-summary-notebook": ["RTP_index", "RTP_congestion", "RTP_topsheet", "RTP_MIC", "RTP_person", "RTP_household", "RTP_access", "RTP_costs", "RTP_walk_bike", "RTP_emissions", "RTP_mode_share", "RTP_freight", "RTP_transit"], "activitysim-validation-notebook": ["work_from_home", "auto_ownership", "telecommute_frequency", "free_parking", "cdap", "intermediate_stop_frequency", "trip_purpose", "trip_destination_choice", "school_location", "work_location", "mandatory_tour_frequency", "mandatory_tour_scheduling", "non_mandatory_tour_frequency", "non_mandatory_tour_destination_choice", "non_mandatory_tour_scheduling", "joint_tour_frequency", "joint_tour_composition", "atwork_subtours_frequency", "atwork_subtours_destination_choice", "atwork_subtours_scheduling", "atwork_subtour_mode", "tour_mode_choice", "trip_mode_choice"], "network-validation-notebook": ["JBLM", "supplementals", "transit_validation", "traffic_validation", "bike_validation", "link_analysis"], "run-comparison-notebook": ["topsheet", "population", "parking", "vmt", "transit"]}, "p_output_dir": "outputs/summary", "output_folder": "outputs", "survey_folder": "inputs/base_year/survey", "uncloned_folder": "uncloned", "sc_run_name": "current run", "sc_run_path": "../../../../", "survey_directories": {"survey": "../../../../inputs/base_year/survey"}, "comparison_runs_list": {"2050 new transit, old network": "\\\\modelstation3\\c$\\Workspace\\sc_new_2050_transit\\soundcast", "2050 urbansim": "\\\\modelstation2\\c$\\Workspace\\sc_2050_urbansim2_07_30_25"}, "county_map": {"33": "King", "35": "Kitsap", "53": "Pierce", "61": "Snohomish"}, "uc_list": ["@sov_inc1", "@sov_inc2", "@sov_inc3", "@hov2_inc1", "@hov2_inc2", "@hov2_inc3", "@hov3_inc1", "@hov3_inc2", "@hov3_inc3", "@av_sov_inc1", "@av_sov_inc2", "@av_sov_inc3", "@av_hov2_inc1", "@av_hov2_inc2", "@av_hov2_inc3", "@av_hov3_inc1", "@av_hov3_inc2", "@av_hov3_inc3", "@tnc_inc1", "@tnc_inc2", "@tnc_inc3", "@mveh", "@hveh", "@bveh"], "agency_lookup": {"1": "King County Metro", "2": "Pierce Transit", "3": "Community Transit", "4": "Kitsap Transit", "5": "Washington Ferries", "6": "Sound Transit", "7": "Everett Transit"}, "emissions_scenario": "standard", "tot_veh_model_base_year": 3185281, "speed_bins": [-999999.0, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5, 37.5, 42.5, 47.5, 52.5, 57.5, 62.5, 67.5, 72.5, 999999.0], "fac_type_lookup": {"0": 0, "1": 4, "2": 4, "3": 5, "4": 5, "5": 5, "6": 3, "7": 5, "8": 0}, "tod_lookup": {"5to9": 5, "9to15": 9, "15to18": 15, "18to20": 18, "20to5": 20}, "summer_list": [87], "special_route_lookup": {"1671": "A-Line Rapid Ride", "1672": "B-Line Rapid Ride", "1673": "C-Line Rapid Ride", "1674": "D-Line Rapid Ride", "1675": "E-Line Rapid Ride", "1677": "H-Line Rapid Ride", "4950": "Central Link", "6995": "Tacoma Link", "6998": "Sounder South", "6999": "Sounder North", "3701": "Swift Blue Line", "3702": "Swift Green Line"}}
input_config = {"debug_skims_and_paths": False, "model_year": "2023", "base_year": "2023", "landuse_inputs": "23_on_23_v3", "network_inputs": "base_year_2023_final", "db_name": "soundcast_inputs_2023.db", "soundcast_inputs_dir": "R:/e2projects_two/SoundCast/Inputs/rtp_2026_2050", "abm_model": "daysim", "run_accessibility_calcs": False, "run_setup_emme_project_folders": False, "run_setup_emme_bank_folders": False, "run_copy_scenario_inputs": False, "run_import_networks": False, "run_skims_and_paths_free_flow": False, "run_skims_and_paths": False, "run_truck_model": False, "run_supplemental_trips": False, "run_daysim": False, "run_summaries": True, "include_av": False, "include_tnc": True, "tnc_av": False, "include_tnc_to_transit": False, "include_knr_to_transit": False, "include_delivery": False, "include_telecommute": True, "run_integrated": False, "should_build_shadow_price": False, "delete_banks": False, "include_tnc_emissions": True, "add_distance_pricing": False, "distance_rate_dict": {"am": 13.5, "md": 8.5, "pm": 13.5, "ev": 8.5, "ni": 8.5}}

---
title: "Walk and Bike"
date: today
---

In [2]:
import pandas as pd
import polars as pl
import util
from pathlib import Path

pd.set_option('display.float_format', '{:,.0f}'.format)

## Average Miles Walking and Biking per Day by Resident

In [3]:
# trip,person,vmt data
person_trips = pd.read_csv(util.output_path / 'agg/dash/person_trips.csv')
person = pd.read_csv(util.output_path / 'agg/dash/person_geog.csv')
vmt = pd.read_csv(util.output_path / 'agg/dash/person_vmt.csv')

# list of equity geographies
equity_geogs = util.summary_config['hh_equity_geogs']

# TRIPS
df_trip = person_trips.copy()

# add home RGC
df_trip = util.get_is_rgc(df_trip, 'hh_rgc')
# add trip type
df_trip.loc[df_trip['dpurp'] != 'Work', 'trip_type'] = 'Non-Work'
df_trip.loc[df_trip['dpurp'] == 'Work', 'trip_type'] = 'Work'

# PERSONS
df_person = person.copy()
# add home RGC
df_person = util.get_is_rgc(df_person, 'hh_rgc')

# VMT
df_vmt = vmt.copy()
# add home RGC
df_vmt = util.get_is_rgc(df_vmt, 'hh_rgc')

# Select only walk and bike trips
df_vmt_bp = df_vmt[df_vmt['mode'].isin(['Walk','Bike'])].copy()
# Select only drivers (dorp = 1) and auto trips
df_vmt = df_vmt[df_vmt['mode'].isin(['SOV','HOV2','HOV3+']) & (df_vmt['dorp'] == 1)].copy()

# total population by equity geography
equity_geogs_population = df_person[equity_geogs].apply(lambda x: x * df_person['psexpfac']).sum().reset_index()
equity_geogs_population.columns = ['Equity Group', 'psexpfac']

df_vmt_bp2 = df_vmt_bp.copy()
df_vmt_bp2['mode'] = 'Walk and Bike'
# add walk and bike
df_vmt_bp2 = pd.concat([df_vmt_bp, df_vmt_bp2])

In [4]:
def walk_bike_per_person(geog, map=False):
    
    # miles by mode and geography
    df1 = df_vmt_bp2.groupby([geog, 'mode'], as_index=False)['travdist_wt'].sum().set_index(geog)

    if map:
        df1.index = df1.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })

    # add total miles in region
    df1_region = df_vmt_bp2.groupby(['mode'])['travdist_wt'].sum().reset_index()
    df1_region[geog] = 'Region'
    df1_region = df1_region.set_index(geog)
    df1 = pd.concat([df1, df1_region])

    # population by geography
    df3 = df_person.groupby(geog, as_index=False)['psexpfac'].sum().set_index(geog)
    if map:
        df3.index = df3.index.astype('int').map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population',
                                })
    df3.loc['Region',:] = df3.sum(axis=0)

    # calculate average miles per person
    df = df1.merge(df3, on=geog)
    df['Average Miles per Person'] = df['travdist_wt']/df['psexpfac']

    return df.pivot(columns='mode', values='Average Miles per Person')

:::{.panel-tabset}

### County and Region

In [5]:
pd.set_option('display.float_format', '{:,.2f}'.format)
walk_bike_per_person('hh_county')

mode       Bike  Walk  Walk and Bike
hh_county
King       0.21  0.58           0.79
Kitsap     0.14  0.52           0.66
Pierce     0.17  0.48           0.65
Region     0.19  0.53           0.72
Snohomish  0.17  0.47           0.63

### Regional Growth Center

In [6]:
walk_bike_per_person('is_rgc')

mode        Bike  Walk  Walk and Bike
is_rgc
In RGC      0.26  1.05           1.31
Not in RGC  0.18  0.50           0.68
Region      0.19  0.53           0.72

In [7]:
walk_bike_per_person('hh_rgc')

mode                             Bike  Walk  Walk and Bike
hh_rgc
Auburn                           0.40  0.67           1.07
Bellevue                         0.27  0.87           1.14
Bothell Canyon Park              0.27  0.49           0.76
Bremerton                        0.22  0.93           1.15
Burien                           0.33  0.57           0.90
Everett                          0.17  0.74           0.91
Federal Way                      0.35  0.69           1.04
Greater Downtown Kirkland        0.24  0.63           0.87
Kent                             0.26  0.64           0.90
Kirkland Totem Lake              0.22  0.55           0.77
Lakewood                         0.30  0.61           0.90
Lynnwood                         0.24  0.65           0.89
Not in RGC                       0.18  0.50           0.68
Puyallup Downtown                0.21  0.63           0.83
Puyallup South Hill              0.17  0.59           0.76
Redmond Downtown                 0.30  0.69           0.99
Redmond-Overlake                 0.30  0.73           1.03
Region                           0.19  0.53           0.72
Renton                           0.40  0.66           1.06
SeaTac                           0.27  0.62           0.89
Seattle Downtown                 0.19  1.39           1.58
Seattle First Hill/Capitol Hill  0.26  1.47           1.73
Seattle Northgate                0.32  0.77           1.09
Seattle South Lake Union         0.24  1.30           1.54
Seattle University Community     0.41  1.00           1.41
Seattle Uptown                   0.33  1.25           1.58
Silverdale                       0.10  0.69           0.79
Tacoma Downtown                  0.23  0.98           1.21
Tacoma Mall                      0.30  0.76           1.06
Tukwila                          0.28  0.63           0.91
University Place                 0.18  0.59           0.77

### Regional Geography

In [8]:
walk_bike_per_person('hh_rg_proposed')

mode                               Bike  Walk  Walk and Bike
hh_rg_proposed
Cities and Towns                   0.14  0.44           0.58
Core Cities                        0.20  0.50           0.70
High Capacity Transit Communities  0.18  0.48           0.66
Metropolitan Cities                0.22  0.73           0.95
Region                             0.19  0.53           0.72
Rural Areas                        0.16  0.32           0.48
Urban Unincorporated Areas         0.15  0.44           0.59

### Equity Focus Areas

In [9]:
efa_col_dict = {
    "People of Color": "hh_efa_poc",
    "Income": "hh_efa_pov200",
    "LEP": "hh_efa_lep",
    "Disability": "hh_efa_dis",
    "Older Adults": "hh_efa_older",
    "Youth": "hh_efa_youth"
    }

In [10]:
df = pd.DataFrame()
for label, col in efa_col_dict.items():
    _df = walk_bike_per_person(col, map=True)
    _df = _df.drop('Region', axis=0)
    _df['Group'] = label
    df = pd.concat([df, _df])
df = df.reset_index()
df.rename(columns={'index': 'EFA Type'}, inplace=True)
df

mode,EFA Type,Bike,Walk,Walk and Bike,Group
0,Above Regional Average,0.20,0.57,0.76,People of Color
1,Below Regional Average,0.18,0.51,0.68,People of Color
2,Higher Share of Equity Population,0.22,0.56,0.77,People of Color
3,Above Regional Average,0.19,0.55,0.74,Income
4,Below Regional Average,0.18,0.51,0.69,Income
5,Higher Share of Equity Population,0.22,0.61,0.83,Income
6,Above Regional Average,0.20,0.53,0.72,LEP
7,Below Regional Average,0.18,0.53,0.71,LEP
8,Higher Share of Equity Population,0.21,0.54,0.75,LEP
9,Above Regional Average,0.19,0.53,0.72,Disability
10,Below Regional Average,0.19,0.52,0.71,Disability
11,Higher Share of Equity Population,0.18,0.59,0.77,Disability
12,Above Regional Average,0.18,0.50,0.68,Older Adults
13,Below Regional Average,0.20,0.56,0.76,Older Adults
14,Higher Share of Equity Population,0.18,0.51,0.69,Older Adults
15,Above Regional Average,0.17,0.47,0.64,Youth
16,Below Regional Average,0.21,0.61,0.82,Youth
17,Higher Share of Equity Population,0.17,0.44,0.60,Youth

:::

## Median Trip Distance by Mode and Home Location

:::{.panel-tabset}

### County

In [11]:
trip = pl.read_csv(util.output_path / 'daysim/_trip.tsv',separator='\t')
hh = pl.read_csv(util.output_path / 'daysim/_household.tsv',separator='\t')

list_cols = ['ParcelID','CountyName','GrowthCenterName','rg_proposed', 'People of Color', 'Income', 'LEP', 'Disability',
       'Older Adults', 'Youth']
parcel_geog = util.get_parcel_geog()[list_cols]

In [12]:
# trip table with home location
df_trip_hh = trip.join(hh, on="hhno", how="left").to_pandas()
df_trip_hh = df_trip_hh.merge(parcel_geog, how='left', left_on='hhparcel', right_on='ParcelID')
df_trip_hh['mode_label'] = df_trip_hh['mode'].map(
    {1: 'Walk',
     2: 'Bike',
     3: 'Drive Alone',
     4: 'Shared Ride',
     5: 'Shared Ride',
     6: 'Transit'}
     )

df_trip_hh = df_trip_hh[df_trip_hh['CountyName']!='Outside Region']
df_trip_hh = util.get_is_rgc(df_trip_hh, 'GrowthCenterName', 'is_rgc')

In [13]:
def get_median_time_distance(df, geog, value_col):

    df_geog = pd.pivot_table(df, index=geog, columns='mode_label', aggfunc='median', values=value_col)
    
    return df_geog


df = get_median_time_distance(df_trip_hh,'CountyName','travdist')
df_region =  get_median_time_distance(df_trip_hh,None,'travdist')
df.loc['Region'] = df_region.iloc[0]
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
CountyName
King        1.69         3.59         2.72     4.17  0.66
Kitsap      1.70         3.07         2.49    13.56  0.72
Pierce      1.85         3.76         2.82     3.97  0.82
Snohomish   1.82         3.82         2.68     4.06  0.83
Region      1.75         3.63         2.72     4.35  0.71

### Regional Geography

In [14]:
df = get_median_time_distance(df_trip_hh,'rg_proposed','travdist')
df

mode_label,Bike,Drive Alone,Shared Ride,Transit,Walk
rg_proposed,,,,,
Cities and Towns,1.56,4.39,2.64,8.21,0.76
Core Cities,1.90,3.46,2.57,6.66,0.82
High Capacity Transit Communities,1.90,3.76,2.71,8.03,0.86
Metropolitan Cities,1.46,2.54,1.99,3.34,0.60
Rural Areas,2.99,6.36,5.28,14.33,0.95
Urban Unincorporated Areas,2.02,4.25,3.07,9.04,1.01

### Regional Growth Center

In [15]:
df = get_median_time_distance(df_trip_hh,'is_rgc','travdist')
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
is_rgc
In RGC      1.04         1.71         1.41     1.70  0.46
Not in RGC  1.90         3.73         2.77     5.16  0.80

In [16]:
df = get_median_time_distance(df_trip_hh,'GrowthCenterName','travdist')
df

mode_label                       Bike  Drive Alone  Shared Ride  Transit  Walk
GrowthCenterName
Auburn                           1.76         2.31         1.65     9.57  0.43
Bellevue                         0.79         1.38         0.99     7.16  0.36
Bothell Canyon Park              3.09         3.44         2.55     9.98  0.65
Bremerton                        1.19         1.49         1.14    23.77  0.44
Burien                           1.31         4.23         2.75     8.23  0.42
Everett                          0.88         1.17         0.89     1.17  0.40
Federal Way                      1.77         2.48         1.74     2.27  0.49
Greater Downtown Kirkland        1.91         3.22         2.34     9.35  0.50
Kent                             1.67         2.38         1.93     7.18  0.41
Kirkland Totem Lake              1.48         2.80         1.79     6.11  0.73
Lakewood                         1.10         1.45         1.21     3.63  0.48
Lynnwood                         1.75         2.09         1.75     5.90  0.58
Not in RGC                       1.90         3.73         2.77     5.16  0.80
Puyallup Downtown                1.14         2.25         1.39    10.03  0.51
Puyallup South Hill              1.47         2.03         1.61    13.85  0.62
Redmond Downtown                 1.38         2.32         1.40     4.45  0.47
Redmond-Overlake                 1.37         1.68         1.25     4.04  0.54
Renton                           1.96         2.89         2.10     5.99  0.45
SeaTac                           1.74         3.21         2.66     4.95  0.71
Seattle Downtown                 0.76         0.90         0.87     0.97  0.38
Seattle First Hill/Capitol Hill  1.03         1.19         1.04     1.29  0.51
Seattle Northgate                1.97         2.68         1.99     6.53  0.63
Seattle South Lake Union         0.87         1.09         1.02     1.24  0.41
Seattle University Community     1.11         2.27         1.91     3.79  0.66
Seattle Uptown                   1.16         1.38         1.14     1.58  0.51
Silverdale                       0.84         0.91         0.81    35.41  0.50
Tacoma Downtown                  1.10         1.49         1.26     1.65  0.49
Tacoma Mall                      1.67         1.82         1.47     3.49  0.63
Tukwila                          2.00         2.26         2.38     9.75  0.49
University Place                 1.40         2.44         1.65     4.01  0.64

### Equity Focus Areas

In [17]:
df = pd.DataFrame()
for col in efa_col_dict.keys():
    _df = get_median_time_distance(df_trip_hh,col,'travdist').reset_index()
    _df['Group'] = col
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

mode_label                                         Bike  Drive Alone  \
Group           EFA Type
People of Color Above Regional Average             1.66         3.42
                Below Regional Average             1.80         3.81
                Higher Share of Equity Population  1.76         3.51
Income          Above Regional Average             1.69         3.35
                Below Regional Average             1.80         3.90
                Higher Share of Equity Population  1.65         2.96
LEP             Above Regional Average             1.81         3.75
                Below Regional Average             1.70         3.66
                Higher Share of Equity Population  1.85         3.40
Disability      Above Regional Average             1.72         3.55
                Below Regional Average             1.81         3.77
                Higher Share of Equity Population  1.61         3.17
Older Adults    Above Regional Average             1.81         3.82
                Below Regional Average             1.70         3.47
                Higher Share of Equity Population  1.88         3.85
Youth           Above Regional Average             1.92         3.99
                Below Regional Average             1.62         3.18
                Higher Share of Equity Population  1.91         4.51

mode_label                                         Shared Ride  Transit  Walk
Group           EFA Type
People of Color Above Regional Average                    2.56     3.46  0.69
                Below Regional Average                    2.86     4.86  0.73
                Higher Share of Equity Population         2.65     4.69  0.71
Income          Above Regional Average                    2.50     4.39  0.70
                Below Regional Average                    2.92     4.63  0.72
                Higher Share of Equity Population         2.35     3.89  0.70
LEP             Above Regional Average                    2.77     4.36  0.73
                Below Regional Average                    2.77     4.12  0.69
                Higher Share of Equity Population         2.53     5.27  0.79
Disability      Above Regional Average                    2.66     4.75  0.71
                Below Regional Average                    2.83     4.40  0.74
                Higher Share of Equity Population         2.44     3.01  0.65
Older Adults    Above Regional Average                    2.88     4.70  0.72
                Below Regional Average                    2.57     3.93  0.71
                Higher Share of Equity Population         3.03     6.58  0.71
Youth           Above Regional Average                    2.92     5.97  0.83
                Below Regional Average                    2.45     3.88  0.64
                Higher Share of Equity Population         3.08     6.57  0.90

:::

## Median Time Spent Walking/Biking
Time in minutes

:::{.panel-tabset}

### County

In [18]:

df = get_median_time_distance(df_trip_hh,'CountyName','travtime')
df_region =  get_median_time_distance(df_trip_hh,None,'travtime')
df.loc['Region'] = df_region.iloc[0]
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
CountyName
King       11.27        12.34        10.35    24.84 13.15
Kitsap     11.31        10.67         9.53    73.79 14.34
Pierce     12.33        12.26        10.51    35.85 16.33
Snohomish  12.10        11.69         9.43    30.75 16.52
Region     11.65        12.08        10.15    26.80 14.23

### Regional Geography

In [19]:
df = get_median_time_distance(df_trip_hh,'rg_proposed','travtime')
df

mode_label,Bike,Drive Alone,Shared Ride,Transit,Walk
rg_proposed,,,,,
Cities and Towns,10.40,12.26,9.34,44.11,15.25
Core Cities,12.69,11.20,9.47,38.91,16.37
High Capacity Transit Communities,12.67,11.71,9.65,41.23,17.14
Metropolitan Cities,9.76,11.51,9.86,21.24,11.96
Rural Areas,19.91,15.80,14.25,61.29,19.02
Urban Unincorporated Areas,13.45,12.30,10.29,48.81,20.24

### Regional Growth Center

In [20]:
df = get_median_time_distance(df_trip_hh,'is_rgc','travtime')
df

mode_label  Bike  Drive Alone  Shared Ride  Transit  Walk
is_rgc
In RGC      6.95        10.62         9.42    15.51  9.17
Not in RGC 12.66        12.18        10.18    30.48 15.94

In [21]:
df = get_median_time_distance(df_trip_hh,'GrowthCenterName','travtime')
df

mode_label                       Bike  Drive Alone  Shared Ride  Transit  Walk
GrowthCenterName
Auburn                          11.71         9.81         8.46    46.65  8.50
Bellevue                         5.24         8.13         7.11    28.29  7.14
Bothell Canyon Park             20.63        11.09         9.67    39.42 12.92
Bremerton                        7.94         9.93         9.34    65.06  8.76
Burien                           8.73        11.59         9.14    40.44  8.36
Everett                          5.86         7.49         6.75    13.98  7.97
Federal Way                     11.77         8.83         7.49    24.37  9.70
Greater Downtown Kirkland       12.73        10.44         9.00    37.52  9.96
Kent                            11.13         8.82         7.35    40.45  8.13
Kirkland Totem Lake              9.85         9.66         7.77    36.73 14.69
Lakewood                         7.34         8.64         7.98    27.10  9.69
Lynnwood                        11.64         9.22         8.55    32.49 11.60
Not in RGC                      12.66        12.18        10.18    30.48 15.94
Puyallup Downtown                7.60         9.10         7.98    53.66 10.11
Puyallup South Hill              9.80         8.33         7.24    68.38 12.42
Redmond Downtown                 9.23         8.16         6.26    29.63  9.42
Redmond-Overlake                 9.12         7.50         6.11    26.47 10.71
Renton                          13.07        10.89         9.33    32.94  8.93
SeaTac                          11.57        11.32        10.21    34.57 14.12
Seattle Downtown                 5.06        10.98        10.67     7.57  7.65
Seattle First Hill/Capitol Hill  6.89        11.01        10.36    12.89 10.11
Seattle Northgate               13.16        11.11         9.41    24.95 12.65
Seattle South Lake Union         5.83        11.25        10.93    11.28  8.24
Seattle University Community     7.40        12.32        11.43    18.57 13.29
Seattle Uptown                   7.71        11.75        10.96    13.70 10.27
Silverdale                       5.61         5.17         4.78    88.59 10.04
Tacoma Downtown                  7.33        11.20        10.59    16.83  9.82
Tacoma Mall                     11.16         9.64         8.93    28.54 12.51
Tukwila                         13.34         8.80         8.59    33.45  9.84
University Place                 9.31        10.37         8.42    33.20 12.90

### Equity Focus Areas

In [22]:
df = pd.DataFrame()
for col in efa_col_dict.keys():
    _df = get_median_time_distance(df_trip_hh,col,'travtime').reset_index()
    _df['Group'] = col
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

mode_label                                         Bike  Drive Alone  \
Group           EFA Type
People of Color Above Regional Average            11.09        11.59
                Below Regional Average            12.00        12.49
                Higher Share of Equity Population 11.71        11.74
Income          Above Regional Average            11.24        11.57
                Below Regional Average            12.03        12.54
                Higher Share of Equity Population 11.01        11.06
LEP             Above Regional Average            12.04        11.92
                Below Regional Average            11.34        12.35
                Higher Share of Equity Population 12.33        11.39
Disability      Above Regional Average            11.43        11.89
                Below Regional Average            12.04        12.37
                Higher Share of Equity Population 10.76        11.40
Older Adults    Above Regional Average            12.04        12.41
                Below Regional Average            11.31        11.82
                Higher Share of Equity Population 12.54        12.32
Youth           Above Regional Average            12.83        12.29
                Below Regional Average            10.80        11.77
                Higher Share of Equity Population 12.71        12.84

mode_label                                         Shared Ride  Transit  Walk
Group           EFA Type
People of Color Above Regional Average                    9.74    23.81 13.88
                Below Regional Average                   10.48    27.09 14.50
                Higher Share of Equity Population         9.96    30.07 14.15
Income          Above Regional Average                    9.77    27.06 14.01
                Below Regional Average                   10.46    27.52 14.41
                Higher Share of Equity Population         9.63    24.48 14.04
LEP             Above Regional Average                    9.99    29.06 14.57
                Below Regional Average                   10.41    24.45 13.73
                Higher Share of Equity Population         9.60    31.79 15.75
Disability      Above Regional Average                   10.02    29.42 14.17
                Below Regional Average                   10.30    26.09 14.71
                Higher Share of Equity Population         9.87    24.38 13.03
Older Adults    Above Regional Average                   10.51    29.73 14.35
                Below Regional Average                    9.81    24.28 14.18
                Higher Share of Equity Population        10.78    34.23 14.22
Youth           Above Regional Average                   10.20    35.45 16.68
                Below Regional Average                   10.04    23.53 12.81
                Higher Share of Equity Population        10.36    39.83 18.10

:::

## % Population Walking or Biking for Transportation
Does not include people making exercise trips

In [23]:
bike_walk_trips = trip.filter(pl.col("mode").is_in([1, 2]))

# Get unique persons with at least one bike/walk trip
bike_walk_persons = bike_walk_trips.select(["hhno", "pno"]).unique()
bike_walk_persons = bike_walk_persons.with_columns(bike_walk=pl.lit(1))

# Join back to all persons, mark bike_walk as False if not present
person = pl.read_csv(util.output_path / 'daysim/_person.tsv',separator='\t')
person_with_bike_walk = person.join(bike_walk_persons, on=["hhno", "pno"], how="left")
person_with_bike_walk = person_with_bike_walk.join(hh, on='hhno', how='left')

person_with_bike_walk = person_with_bike_walk.to_pandas()
person_with_bike_walk = person_with_bike_walk.merge(parcel_geog, how='left', left_on='hhparcel', right_on='ParcelID')

person_with_bike_walk['bike_walk'] = person_with_bike_walk['bike_walk'].fillna(0)


person_with_bike_walk = person_with_bike_walk[person_with_bike_walk['CountyName']!='Outside Region']
person_with_bike_walk = util.get_is_rgc(person_with_bike_walk, 'GrowthCenterName', 'is_rgc')

:::{.panel-tabset}
### County

In [24]:
def get_pop_bike_walk(df, geog):
    df = pd.pivot_table(df, index=geog, columns='bike_walk', aggfunc='sum', values='psexpfac')
    df['% Biking or Walking'] = df[1]/(df[0]+df[1])
    return df[['% Biking or Walking']]

In [25]:
pd.set_option('display.float_format', '{:.1%}'.format)
df = get_pop_bike_walk(person_with_bike_walk, 'CountyName')
df_region =  get_pop_bike_walk(person_with_bike_walk, None)
df.loc['Region'] = df_region.iloc[0]
df

bike_walk   % Biking or Walking
CountyName
King                      28.6%
Kitsap                    24.9%
Pierce                    21.8%
Snohomish                 21.8%
Region                    25.6%

### Regional Geography

In [26]:
df = get_pop_bike_walk(person_with_bike_walk, 'rg_proposed')
df

bike_walk                          % Biking or Walking
rg_proposed
Cities and Towns                                 22.3%
Core Cities                                      23.5%
High Capacity Transit Communities                22.1%
Metropolitan Cities                              37.3%
Rural Areas                                      12.9%
Urban Unincorporated Areas                       18.7%

### Regional Growth Center

In [27]:
df = get_pop_bike_walk(person_with_bike_walk, 'is_rgc')
df

bike_walk   % Biking or Walking
is_rgc
In RGC                    56.9%
Not in RGC                23.5%

In [28]:
df = get_pop_bike_walk(person_with_bike_walk, 'GrowthCenterName')
df

bike_walk                        % Biking or Walking
GrowthCenterName
Auburn                                         39.3%
Bellevue                                       59.6%
Bothell Canyon Park                            25.9%
Bremerton                                      52.6%
Burien                                         36.8%
Everett                                        50.1%
Federal Way                                    36.8%
Greater Downtown Kirkland                      35.3%
Kent                                           40.3%
Kirkland Totem Lake                            28.5%
Lakewood                                       36.4%
Lynnwood                                       34.0%
Not in RGC                                     23.5%
Puyallup Downtown                              37.1%
Puyallup South Hill                            32.9%
Redmond Downtown                               41.7%
Redmond-Overlake                               42.4%
Renton                                         36.2%
SeaTac                                         30.6%
Seattle Downtown                               79.4%
Seattle First Hill/Capitol Hill                72.7%
Seattle Northgate                              39.0%
Seattle South Lake Union                       71.6%
Seattle University Community                   52.3%
Seattle Uptown                                 64.5%
Silverdale                                     41.7%
Tacoma Downtown                                52.4%
Tacoma Mall                                    38.4%
Tukwila                                        36.2%
University Place                               32.2%

### Equity Focus Areas

In [29]:
df = pd.DataFrame()
for col in efa_col_dict.keys():
    _df = get_pop_bike_walk(person_with_bike_walk,col).reset_index()
    _df['Group'] = col
    _df.rename(columns={col: 'EFA Type'}, inplace=True)
    df = pd.concat([df, _df])

df.set_index(['Group','EFA Type'])

bike_walk                                          % Biking or Walking
Group           EFA Type
People of Color Above Regional Average                           27.1%
                Below Regional Average                           24.4%
                Higher Share of Equity Population                26.8%
Income          Above Regional Average                           26.6%
                Below Regional Average                           24.3%
                Higher Share of Equity Population                29.3%
LEP             Above Regional Average                           24.7%
                Below Regional Average                           25.9%
                Higher Share of Equity Population                25.5%
Disability      Above Regional Average                           25.5%
                Below Regional Average                           25.0%
                Higher Share of Equity Population                28.2%
Older Adults    Above Regional Average                           24.0%
                Below Regional Average                           27.1%
                Higher Share of Equity Population                23.8%
Youth           Above Regional Average                           21.6%
                Below Regional Average                           30.0%
                Higher Share of Equity Population                20.2%

:::

## Bike and Walk Tours by Purpose
Tours where most or all trips are by the mode.

In [30]:
df = pd.read_csv(util.output_path / 'agg/dash/tour_total.csv')

df['Tour Mode'] = df['tmodetp'].map({'SOV': 'Drove Alone',
                                     'HOV2': 'Shared Ride',
                                     'HOV3+': 'Shared Ride',
                                     'Transit': 'Transit',
                                     'Walk': 'Walk',
                                     'Bike': 'Bike'
                                     })

df = pd.pivot_table(df, index='pdpurp', columns='Tour Mode', values='toexpfac', aggfunc='sum')
df = df/df.sum()
df[['Transit', 'Walk', 'Bike','Drove Alone', 'Shared Ride', ]]

Tour Mode          Transit  Walk  Bike  Drove Alone  Shared Ride
pdpurp
Escort                0.0%  7.1%  2.8%         1.0%        22.8%
Meal                  8.6% 10.2%  1.7%         4.9%         7.5%
Personal Business    12.7%  5.6%  4.1%         8.3%         5.8%
School               20.0%  4.1% 16.2%         4.2%        11.8%
Shop                 16.4% 11.9%  7.9%        15.4%        10.9%
Social               18.7% 51.9% 39.2%        20.9%        22.6%
Work                 23.6%  9.1% 28.1%        45.4%        18.6%

## Average Jobs Accessible within 1 Mile Walk and 3 Mile Bike
Note that this is not using the bike network, but is instead using the all-streets network.

Average accessible jobs are weighted averages based on parcel household population.

In [31]:
# total jobs
parcel_emp = util.get_parcels_urbansim_data()[['parcelid','emptot_p']]
tot_jobs = parcel_emp['emptot_p'].sum()

In [32]:
walk_bike_jobs_access = pd.read_csv(util.output_path / 'access/walk_bike_jobs_access.csv', 
                                  usecols=['geography_value', 'jobs_1_mile_walk', 'jobs_3_mile_bike', 'geography_group']).\
                                  rename(columns={'geography_value': 'geography'})

df_access = walk_bike_jobs_access.copy()
df_access = df_access[df_access['geography'] != 'Outside Region']
# rename region
df_access.loc[df_access['geography_group'] == 'region', 'geography'] = 'Region'
# rename rgc
df_access.loc[df_access['geography_group'] == 'rgc_binary', 'geography'] = ['Not in RGC', 'In RGC']
# rename efa 
# jobs access in equity geographies
equity_geogs = util.summary_config['equity_geogs']
df_access.loc[df_access['geography_group'].isin(equity_geogs), 'geography'] = df_access.loc[df_access['geography_group'].isin(equity_geogs), 'geography'].\
    map({"0.0": 'Below Regional Average', 
         "1.0": 'Above Regional Average', 
         "2.0": 'Higher Share of Equity Population'}
         )

:::{.panel-tabset}

### Region and County

In [33]:
def bp_job_access_geog(access_table,geog):
    df = access_table.loc[access_table['geography_group'].isin(geog)].\
        rename(columns={'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                        'jobs_3_mile_bike': 'Jobs within 3-mile Bike'}).\
        drop(columns=['geography_group']).\
        set_index('geography')

    df['% Total Jobs (1-mile Walk)'] = df['Jobs within 1-mile Walk'].apply(lambda x: x / tot_jobs)
    df['% Total Jobs (3-mile Bike)'] = df['Jobs within 3-mile Bike'].apply(lambda x: x / tot_jobs)

    

    return df

format_dict = {
        'Jobs within 1-mile Walk': "{:.0f}",
        'Jobs within 3-mile Bike': "{:.0f}", 
        '% Total Jobs (1-mile Walk)': "{:.1%}", 
        '% Total Jobs (3-mile Bike)': "{:.1%}"
    }

In [34]:
df = bp_job_access_geog(df_access,['region','CountyName'])
df.style.format(format_dict)

### Regional Growth Center

In [35]:
df = bp_job_access_geog(df_access,['rgc_binary'])
df.style.format(format_dict)

In [36]:
df = bp_job_access_geog(df_access,['GrowthCenterName'])
df.style.format(format_dict)

### Regional Geography

In [37]:
df = bp_job_access_geog(df_access,['rg_proposed'])
df.style.format(format_dict)

### Equity Focus Areas

In [38]:
efa_geog_dict = {
    "People of Color": "equity_focus_areas_2023__efa_poc",
    "Income": "equity_focus_areas_2023__efa_pov200",
    "LEP": "equity_focus_areas_2023__efa_lep",
    "Disability": "equity_focus_areas_2023__efa_dis",
    "Older Adults": "equity_focus_areas_2023__efa_older",
    "Youth": "equity_focus_areas_2023__efa_youth"
    }

df = pd.DataFrame()
for label, col in efa_geog_dict.items():
    _df = bp_job_access_geog(df_access,[col])
    _df['Group'] = label
    df = pd.concat([df, _df])
df = df.reset_index()
df.rename(columns={'geography': 'EFA Type'}, inplace=True)
df.set_index(['Group','EFA Type']).style.format(format_dict)

:::