In [ ]:
# import toml
# from pathlib import Path
# config_path = Path("../../../../configuration/asim_configuration")
# input_config = toml.load(config_path/ "input_configuration.toml")
# summary_config = toml.load(config_path/ "summary_configuration.toml")

---
title: Mandatory Tour Scheduling
date: today
---

The mandatory tour scheduling model selects a tour departure and duration period (and therefore a start and end period as well) for each mandatory tour

In [3]:
import pandas as pd
import numpy as np
import plotly.express as px
import os, sys

module_path = os.path.abspath(os.path.join('../../../..')) # or the path to your source code
sys.path.insert(0, module_path)
import util

In [32]:
# read data
tour = util.get_tour_data(summary_config)

m_tour_data = tour.loc[tour['tour_category']=="mandatory"]
ws_tour_data = m_tour_data.loc[m_tour_data['tour_type'].isin(["work","school"])]

In [5]:
m_tour_data.source.value_counts()

source
model     1768696
survey       3521
Name: count, dtype: int64

## tour start time

:::{.panel-tabset}

### mandatory tours

In [6]:
df_plot = m_tour_data.groupby(['source','start'])[['tour_weight']].sum().reset_index()
df_plot['percentage'] = df_plot.groupby(['source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))

fig = px.bar(df_plot, x="start", y="percentage", color="source",barmode="group",
             title="mandatory tour start time")
fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))
fig.update_layout(height=400, width=700, yaxis=dict(tickformat=".0%"), xaxis=dict(dtick="1"))
fig.show()

- number of tours with start time later than 8pm

In [7]:
df_plot.loc[df_plot['start']>=20]

    source  start  tour_weight  percentage
15   model   20.0  5590.000000    0.003161
16   model   21.0  1650.000000    0.000933
17   model   22.0    91.000000    0.000051
18   model   23.0   160.000000    0.000090
34  survey   20.0   785.209498    0.000446
35  survey   21.0   113.801127    0.000065
36  survey   22.0   387.358648    0.000220
37  survey   23.0   235.312989    0.000134

### work/school tours

In [23]:
df_plot = ws_tour_data.groupby(['source','tour_type','start'],observed=True)[['tour_weight']].sum().reset_index()
df_plot['percentage'] = df_plot.groupby(['tour_type','source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))

fig = px.bar(df_plot, x="start", y="percentage", color="source",barmode="group",
             facet_row='tour_type',
             title="work/school tour start time")
fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))
fig.update_layout(height=400, width=700, yaxis1=dict(tickformat=".0%"), yaxis2=dict(tickformat=".0%", matches=None), xaxis=dict(dtick="1"))
fig.show()

C:\Users\Modeller\AppData\Local\Temp\ipykernel_25544\523503083.py:2: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

::: {.callout-warning}

- bars with tour counts fewer than 30

In [24]:
df_plot.loc[df_plot['tour_weight']<30]

Empty DataFrame
Columns: [source, tour_type, start, tour_weight, percentage]
Index: []

:::

- work/school tour count

In [27]:
ws_count = ws_tour_data.groupby(['source','tour_type'],observed=True)[['tour_weight']].sum().reset_index()
ws_count['trip_weight_2017_2019'] = ws_count['tour_weight'].apply(lambda x: round(x,1))
# df_plot['percentage'] = df_plot.groupby(['source'], group_keys=False)['trip_weight_2017_2019']. \
#     apply(lambda x: x / float(x.sum()))
ws_count.sort_values('tour_type', ascending=False)

   source tour_type   tour_weight  trip_weight_2017_2019
1   model    school  7.330460e+05               733046.0
3  survey    school  3.708458e+05               370845.8
0   model      work  1.035650e+06              1035650.0
2  survey      work  1.389914e+06              1389913.7

:::

## tour duration

:::{.panel-tabset}

### mandatory tours

In [28]:
m_tour_data['duration_cal'] = m_tour_data['end'] - m_tour_data['start']

df_plot = m_tour_data.groupby(['source','duration_cal'])[['tour_weight']].sum().reset_index()
df_plot['percentage'] = df_plot.groupby(['source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))

fig = px.bar(df_plot, x="duration_cal", y="percentage", color="source",barmode="group",
             title="mandatory tour duration")
fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))
fig.update_layout(height=400, width=700, yaxis=dict(tickformat=".0%"), xaxis=dict(dtick="1"))
fig.show()

C:\Users\Modeller\AppData\Local\Temp\ipykernel_25544\3604968384.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### work/school tours

In [29]:
ws_tour_data['duration_cal'] = ws_tour_data['end'] - ws_tour_data['start']

df_plot = ws_tour_data.groupby(['source','tour_type','duration_cal'],observed=True)[['tour_weight']].sum().reset_index()
df_plot['percentage'] = df_plot.groupby(['tour_type','source'], group_keys=False)['tour_weight']. \
    apply(lambda x: x / float(x.sum()))

fig = px.bar(df_plot, x="duration_cal", y="percentage", color="source",barmode="group",
             facet_row='tour_type',
             title="work/school tour duration")
fig.for_each_annotation(lambda a: a.update(text = a.text.split("=")[-1]))
fig.update_layout(height=400, width=700, font=dict(size=11), yaxis1=dict(tickformat=".0%"), yaxis2=dict(tickformat=".0%", matches=None), xaxis=dict(dtick="1"))
fig.show()

C:\Users\Modeller\AppData\Local\Temp\ipykernel_25544\2595035219.py:4: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

::: {.callout-warning}

- bars with tour counts fewer than 30

In [30]:
df_plot.loc[df_plot['tour_weight']<30]

   source tour_type  duration_cal  tour_weight  percentage
37  model    school          18.0         20.0    0.000027

:::

:::